INSERT INTO T_COUNTRY (ID, CODE, NAME, CHECK_CANCEL)VALUES (unhex(replace(uuid(),'-','')),'	AF',  'Afghanistan', 0);
INSERT INTO T_COUNTRY (ID, CODE, NAME, CHECK_CANCEL)VALUES (unhex(replace(uuid(),'-','')),'	AL',  'Albanie', 0);
INSERT INTO T_COUNTRY (ID, CODE, NAME, CHECK_CANCEL)VALUES (unhex(replace(uuid(),'-','')),'	DZ',  'Algérie', 0);
INSERT INTO T_COUNTRY (ID, CODE, NAME, CHECK_CANCEL)VALUES (unhex(replace(uuid(),'-','')),'	AS',  'Samoa orientales', 0);
INSERT INTO T_COUNTRY (ID, CODE, NAME, CHECK_CANCEL)VALUES (unhex(replace(uuid(),'-','')),'	AD',  'Andorre', 0);
INSERT INTO T_COUNTRY (ID, CODE, NAME, CHECK_CANCEL)VALUES (unhex(replace(uuid(),'-','')),'	AO',  'Angola', 0);
INSERT INTO T_COUNTRY (ID, CODE, NAME, CHECK_CANCEL)VALUES (unhex(replace(uuid(),'-','')),'	AI',  'Anguilla', 0);
INSERT INTO T_COUNTRY (ID, CODE, NAME, CHECK_CANCEL)VALUES (unhex(replace(uuid(),'-','')),'	AQ',  'Antarctique', 0);
INSERT INTO T_COUNTRY (ID, CODE, NAME, CHECK_CANCEL)VALUES (unhex(replace(uuid(),'-','')),'	AG',  'Antigua-et-Barbuda', 0);
INSERT INTO T_COUNTRY (ID, CODE, NAME, CHECK_CANCEL)VALUES (unhex(replace(uuid(),'-','')),'	AR',  'Argentine', 0);
INSERT INTO T_COUNTRY (ID, CODE, NAME, CHECK_CANCEL)VALUES (unhex(replace(uuid(),'-','')),'	AM',  'Arménie', 0);
INSERT INTO T_COUNTRY (ID, CODE, NAME, CHECK_CANCEL)VALUES (unhex(replace(uuid(),'-','')),'	AW',  'Aruba', 0);
INSERT INTO T_COUNTRY (ID, CODE, NAME, CHECK_CANCEL)VALUES (unhex(replace(uuid(),'-','')),'	AU',  'Australie', 0);
INSERT INTO T_COUNTRY (ID, CODE, NAME, CHECK_CANCEL)VALUES (unhex(replace(uuid(),'-','')),'	AT',  'Autriche', 0);
INSERT INTO T_COUNTRY (ID, CODE, NAME, CHECK_CANCEL)VALUES (unhex(replace(uuid(),'-','')),'	AZ',  'Azerbaïdjan', 0);
INSERT INTO T_COUNTRY (ID, CODE, NAME, CHECK_CANCEL)VALUES (unhex(replace(uuid(),'-','')),'	BS',  'Bahamas', 0);
INSERT INTO T_COUNTRY (ID, CODE, NAME, CHECK_CANCEL)VALUES (unhex(replace(uuid(),'-','')),'	BH',  'Bahreïn', 0);
INSERT INTO T_COUNTRY (ID, CODE, NAME, CHECK_CANCEL)VALUES (unhex(replace(uuid(),'-','')),'	BD',  'Bangladesh', 0);
INSERT INTO T_COUNTRY (ID, CODE, NAME, CHECK_CANCEL)VALUES (unhex(replace(uuid(),'-','')),'	BB',  'Barbade', 0);
INSERT INTO T_COUNTRY (ID, CODE, NAME, CHECK_CANCEL)VALUES (unhex(replace(uuid(),'-','')),'	BY',  'Biélorussie', 0);
INSERT INTO T_COUNTRY (ID, CODE, NAME, CHECK_CANCEL)VALUES (unhex(replace(uuid(),'-','')),'	BE',  'Belgique', 0);
INSERT INTO T_COUNTRY (ID, CODE, NAME, CHECK_CANCEL)VALUES (unhex(replace(uuid(),'-','')),'	BZ',  'Bélize', 0);
INSERT INTO T_COUNTRY (ID, CODE, NAME, CHECK_CANCEL)VALUES (unhex(replace(uuid(),'-','')),'	BJ',  'Bénin', 0);
INSERT INTO T_COUNTRY (ID, CODE, NAME, CHECK_CANCEL)VALUES (unhex(replace(uuid(),'-','')),'	BM',  'Bermudes', 0);
INSERT INTO T_COUNTRY (ID, CODE, NAME, CHECK_CANCEL)VALUES (unhex(replace(uuid(),'-','')),'	BT',  'Bhoutan', 0);
INSERT INTO T_COUNTRY (ID, CODE, NAME, CHECK_CANCEL)VALUES (unhex(replace(uuid(),'-','')),'	BO',  'Bolivie', 0);
INSERT INTO T_COUNTRY (ID, CODE, NAME, CHECK_CANCEL)VALUES (unhex(replace(uuid(),'-','')),'	BA',  'Bosnie-Herzégovine', 0);
INSERT INTO T_COUNTRY (ID, CODE, NAME, CHECK_CANCEL)VALUES (unhex(replace(uuid(),'-','')),'	BW',  'Botswana', 0);
INSERT INTO T_COUNTRY (ID, CODE, NAME, CHECK_CANCEL)VALUES (unhex(replace(uuid(),'-','')),'	BV',  'Bouvet (Île)', 0);
INSERT INTO T_COUNTRY (ID, CODE, NAME, CHECK_CANCEL)VALUES (unhex(replace(uuid(),'-','')),'	BR',  'Brésil', 0);
INSERT INTO T_COUNTRY (ID, CODE, NAME, CHECK_CANCEL)VALUES (unhex(replace(uuid(),'-','')),'	IO',  'Territoire britannique de l Océan Indien', 0);
INSERT INTO T_COUNTRY (ID, CODE, NAME, CHECK_CANCEL)VALUES (unhex(replace(uuid(),'-','')),'	BN',  'Bruneï', 0);
INSERT INTO T_COUNTRY (ID, CODE, NAME, CHECK_CANCEL)VALUES (unhex(replace(uuid(),'-','')),'	BG',  'Bulgarie', 0);
INSERT INTO T_COUNTRY (ID, CODE, NAME, CHECK_CANCEL)VALUES (unhex(replace(uuid(),'-','')),'	BF',  'Burkina Faso', 0);
INSERT INTO T_COUNTRY (ID, CODE, NAME, CHECK_CANCEL)VALUES (unhex(replace(uuid(),'-','')),'	BI',  'Burundi', 0);
INSERT INTO T_COUNTRY (ID, CODE, NAME, CHECK_CANCEL)VALUES (unhex(replace(uuid(),'-','')),'	KH',  'Cambodge', 0);
INSERT INTO T_COUNTRY (ID, CODE, NAME, CHECK_CANCEL)VALUES (unhex(replace(uuid(),'-','')),'	CM',  'Cameroun', 0);
INSERT INTO T_COUNTRY (ID, CODE, NAME, CHECK_CANCEL)VALUES (unhex(replace(uuid(),'-','')),'	CA',  'Canada', 0);
INSERT INTO T_COUNTRY (ID, CODE, NAME, CHECK_CANCEL)VALUES (unhex(replace(uuid(),'-','')),'	CV',  'Cap Vert', 0);
INSERT INTO T_COUNTRY (ID, CODE, NAME, CHECK_CANCEL)VALUES (unhex(replace(uuid(),'-','')),'	KY',  'Caïmans (Îles)', 0);
INSERT INTO T_COUNTRY (ID, CODE, NAME, CHECK_CANCEL)VALUES (unhex(replace(uuid(),'-','')),'	CF',  'République Centrafricaine', 0);
INSERT INTO T_COUNTRY (ID, CODE, NAME, CHECK_CANCEL)VALUES (unhex(replace(uuid(),'-','')),'	TD',  'Tchad', 0);
INSERT INTO T_COUNTRY (ID, CODE, NAME, CHECK_CANCEL)VALUES (unhex(replace(uuid(),'-','')),'	CL',  'Chili', 0);
INSERT INTO T_COUNTRY (ID, CODE, NAME, CHECK_CANCEL)VALUES (unhex(replace(uuid(),'-','')),'	CN',  'Chine', 0);
INSERT INTO T_COUNTRY (ID, CODE, NAME, CHECK_CANCEL)VALUES (unhex(replace(uuid(),'-','')),'	CX',  'Christmas (Île)', 0);
INSERT INTO T_COUNTRY (ID, CODE, NAME, CHECK_CANCEL)VALUES (unhex(replace(uuid(),'-','')),'	CC',  'Cocos / Keeling (Îles)', 0);
INSERT INTO T_COUNTRY (ID, CODE, NAME, CHECK_CANCEL)VALUES (unhex(replace(uuid(),'-','')),'	CO',  'Colombie', 0);
INSERT INTO T_COUNTRY (ID, CODE, NAME, CHECK_CANCEL)VALUES (unhex(replace(uuid(),'-','')),'	KM',  'Comores', 0);
INSERT INTO T_COUNTRY (ID, CODE, NAME, CHECK_CANCEL)VALUES (unhex(replace(uuid(),'-','')),'	CG',  'Congo', 0);
INSERT INTO T_COUNTRY (ID, CODE, NAME, CHECK_CANCEL)VALUES (unhex(replace(uuid(),'-','')),'	CD',  'République Démocratique du Congo', 0);
INSERT INTO T_COUNTRY (ID, CODE, NAME, CHECK_CANCEL)VALUES (unhex(replace(uuid(),'-','')),'	CK',  'Cook (Îles)', 0);
INSERT INTO T_COUNTRY (ID, CODE, NAME, CHECK_CANCEL)VALUES (unhex(replace(uuid(),'-','')),'	CR',  'Costa Rica', 0);
INSERT INTO T_COUNTRY (ID, CODE, NAME, CHECK_CANCEL)VALUES (unhex(replace(uuid(),'-','')),'	CI',  'Côte D Ivoire', 0);
INSERT INTO T_COUNTRY (ID, CODE, NAME, CHECK_CANCEL)VALUES (unhex(replace(uuid(),'-','')),'	HR',  'Croatie', 0);
INSERT INTO T_COUNTRY (ID, CODE, NAME, CHECK_CANCEL)VALUES (unhex(replace(uuid(),'-','')),'	CU',  'Cuba', 0);
INSERT INTO T_COUNTRY (ID, CODE, NAME, CHECK_CANCEL)VALUES (unhex(replace(uuid(),'-','')),'	CY',  'Chypre', 0);
INSERT INTO T_COUNTRY (ID, CODE, NAME, CHECK_CANCEL)VALUES (unhex(replace(uuid(),'-','')),'	CZ',  'République Tchèque', 0);
INSERT INTO T_COUNTRY (ID, CODE, NAME, CHECK_CANCEL)VALUES (unhex(replace(uuid(),'-','')),'	DK',  'Danemark', 0);
INSERT INTO T_COUNTRY (ID, CODE, NAME, CHECK_CANCEL)VALUES (unhex(replace(uuid(),'-','')),'	DJ',  'Djibouti', 0);
INSERT INTO T_COUNTRY (ID, CODE, NAME, CHECK_CANCEL)VALUES (unhex(replace(uuid(),'-','')),'	DM',  'Dominique', 0);
INSERT INTO T_COUNTRY (ID, CODE, NAME, CHECK_CANCEL)VALUES (unhex(replace(uuid(),'-','')),'	DO',  'République Dominicaine', 0);
INSERT INTO T_COUNTRY (ID, CODE, NAME, CHECK_CANCEL)VALUES (unhex(replace(uuid(),'-','')),'	TP',  'Timor-Oriental', 0);
INSERT INTO T_COUNTRY (ID, CODE, NAME, CHECK_CANCEL)VALUES (unhex(replace(uuid(),'-','')),'	EC',  'Equateur', 0);
INSERT INTO T_COUNTRY (ID, CODE, NAME, CHECK_CANCEL)VALUES (unhex(replace(uuid(),'-','')),'	EG',  'Egypte', 0);
INSERT INTO T_COUNTRY (ID, CODE, NAME, CHECK_CANCEL)VALUES (unhex(replace(uuid(),'-','')),'	SV',  'Salvador', 0);
INSERT INTO T_COUNTRY (ID, CODE, NAME, CHECK_CANCEL)VALUES (unhex(replace(uuid(),'-','')),'	GQ',  'Guinée Equatoriale', 0);
INSERT INTO T_COUNTRY (ID, CODE, NAME, CHECK_CANCEL)VALUES (unhex(replace(uuid(),'-','')),'	ER',  'Erythrée', 0);
INSERT INTO T_COUNTRY (ID, CODE, NAME, CHECK_CANCEL)VALUES (unhex(replace(uuid(),'-','')),'	EE',  'Estonie', 0);
INSERT INTO T_COUNTRY (ID, CODE, NAME, CHECK_CANCEL)VALUES (unhex(replace(uuid(),'-','')),'	ET',  'Ethiopie', 0);
INSERT INTO T_COUNTRY (ID, CODE, NAME, CHECK_CANCEL)VALUES (unhex(replace(uuid(),'-','')),'	FK',  'Falkland / Malouines (Îles)', 0);
INSERT INTO T_COUNTRY (ID, CODE, NAME, CHECK_CANCEL)VALUES (unhex(replace(uuid(),'-','')),'	FO',  'Féroé (Îles)', 0);
INSERT INTO T_COUNTRY (ID, CODE, NAME, CHECK_CANCEL)VALUES (unhex(replace(uuid(),'-','')),'	FJ',  'Fiji', 0);
INSERT INTO T_COUNTRY (ID, CODE, NAME, CHECK_CANCEL)VALUES (unhex(replace(uuid(),'-','')),'	FI',  'Finlande', 0);
INSERT INTO T_COUNTRY (ID, CODE, NAME, CHECK_CANCEL)VALUES (unhex(replace(uuid(),'-','')),'	FR',  'France', 0);
INSERT INTO T_COUNTRY (ID, CODE, NAME, CHECK_CANCEL)VALUES (unhex(replace(uuid(),'-','')),'	FX',  'France métropolitaine', 0);
INSERT INTO T_COUNTRY (ID, CODE, NAME, CHECK_CANCEL)VALUES (unhex(replace(uuid(),'-','')),'	GF',  'Guyane française', 0);
INSERT INTO T_COUNTRY (ID, CODE, NAME, CHECK_CANCEL)VALUES (unhex(replace(uuid(),'-','')),'	PF',  'Polynésie française', 0);
INSERT INTO T_COUNTRY (ID, CODE, NAME, CHECK_CANCEL)VALUES (unhex(replace(uuid(),'-','')),'	TF',  'Territoires Antarctiques français', 0);
INSERT INTO T_COUNTRY (ID, CODE, NAME, CHECK_CANCEL)VALUES (unhex(replace(uuid(),'-','')),'	GA',  'Gabon', 0);
INSERT INTO T_COUNTRY (ID, CODE, NAME, CHECK_CANCEL)VALUES (unhex(replace(uuid(),'-','')),'	GM',  'Gambie', 0);
INSERT INTO T_COUNTRY (ID, CODE, NAME, CHECK_CANCEL)VALUES (unhex(replace(uuid(),'-','')),'	GE',  'Géorgie', 0);
INSERT INTO T_COUNTRY (ID, CODE, NAME, CHECK_CANCEL)VALUES (unhex(replace(uuid(),'-','')),'	DE',  'Allemagne', 0);
INSERT INTO T_COUNTRY (ID, CODE, NAME, CHECK_CANCEL)VALUES (unhex(replace(uuid(),'-','')),'	GH',  'Ghana', 0);
INSERT INTO T_COUNTRY (ID, CODE, NAME, CHECK_CANCEL)VALUES (unhex(replace(uuid(),'-','')),'	GI',  'Gibraltar', 0);
INSERT INTO T_COUNTRY (ID, CODE, NAME, CHECK_CANCEL)VALUES (unhex(replace(uuid(),'-','')),'	GR',  'Grèce', 0);
INSERT INTO T_COUNTRY (ID, CODE, NAME, CHECK_CANCEL)VALUES (unhex(replace(uuid(),'-','')),'	GL',  'Groënland', 0);
INSERT INTO T_COUNTRY (ID, CODE, NAME, CHECK_CANCEL)VALUES (unhex(replace(uuid(),'-','')),'	GD',  'Grenade', 0);
INSERT INTO T_COUNTRY (ID, CODE, NAME, CHECK_CANCEL)VALUES (unhex(replace(uuid(),'-','')),'	GP',  'Guadeloupe', 0);
INSERT INTO T_COUNTRY (ID, CODE, NAME, CHECK_CANCEL)VALUES (unhex(replace(uuid(),'-','')),'	GU',  'Guam', 0);
INSERT INTO T_COUNTRY (ID, CODE, NAME, CHECK_CANCEL)VALUES (unhex(replace(uuid(),'-','')),'	GT',  'Guatemala', 0);
INSERT INTO T_COUNTRY (ID, CODE, NAME, CHECK_CANCEL)VALUES (unhex(replace(uuid(),'-','')),'	GN',  'Guinée', 0);
INSERT INTO T_COUNTRY (ID, CODE, NAME, CHECK_CANCEL)VALUES (unhex(replace(uuid(),'-','')),'	GW',  'Guinée-Bissau', 0);
INSERT INTO T_COUNTRY (ID, CODE, NAME, CHECK_CANCEL)VALUES (unhex(replace(uuid(),'-','')),'	GY',  'Guyana', 0);
INSERT INTO T_COUNTRY (ID, CODE, NAME, CHECK_CANCEL)VALUES (unhex(replace(uuid(),'-','')),'	HT',  'Haïti', 0);
INSERT INTO T_COUNTRY (ID, CODE, NAME, CHECK_CANCEL)VALUES (unhex(replace(uuid(),'-','')),'	HM',  'Territoire des Îles Heard et McDonald', 0);
INSERT INTO T_COUNTRY (ID, CODE, NAME, CHECK_CANCEL)VALUES (unhex(replace(uuid(),'-','')),'	VA',  'Vatican', 0);
INSERT INTO T_COUNTRY (ID, CODE, NAME, CHECK_CANCEL)VALUES (unhex(replace(uuid(),'-','')),'	HN',  'Honduras', 0);
INSERT INTO T_COUNTRY (ID, CODE, NAME, CHECK_CANCEL)VALUES (unhex(replace(uuid(),'-','')),'	HK',  'Hong Kong', 0);
INSERT INTO T_COUNTRY (ID, CODE, NAME, CHECK_CANCEL)VALUES (unhex(replace(uuid(),'-','')),'	HU',  'Hongrie', 0);
INSERT INTO T_COUNTRY (ID, CODE, NAME, CHECK_CANCEL)VALUES (unhex(replace(uuid(),'-','')),'	IS',  'Islande', 0);
INSERT INTO T_COUNTRY (ID, CODE, NAME, CHECK_CANCEL)VALUES (unhex(replace(uuid(),'-','')),'	IN',  'Inde', 0);
INSERT INTO T_COUNTRY (ID, CODE, NAME, CHECK_CANCEL)VALUES (unhex(replace(uuid(),'-','')),'	ID',  'Indonésie', 0);
INSERT INTO T_COUNTRY (ID, CODE, NAME, CHECK_CANCEL)VALUES (unhex(replace(uuid(),'-','')),'	IR',  'Iran (République islamique d) ', 0);
INSERT INTO T_COUNTRY (ID, CODE, NAME, CHECK_CANCEL)VALUES (unhex(replace(uuid(),'-','')),'	IQ',  'Irak', 0);
INSERT INTO T_COUNTRY (ID, CODE, NAME, CHECK_CANCEL)VALUES (unhex(replace(uuid(),'-','')),'	IE',  'Irlande', 0);
INSERT INTO T_COUNTRY (ID, CODE, NAME, CHECK_CANCEL)VALUES (unhex(replace(uuid(),'-','')),'	IL',  'Israël', 0);
INSERT INTO T_COUNTRY (ID, CODE, NAME, CHECK_CANCEL)VALUES (unhex(replace(uuid(),'-','')),'	IT',  'Italie', 0);
INSERT INTO T_COUNTRY (ID, CODE, NAME, CHECK_CANCEL)VALUES (unhex(replace(uuid(),'-','')),'	JM',  'Jamaïque', 0);
INSERT INTO T_COUNTRY (ID, CODE, NAME, CHECK_CANCEL)VALUES (unhex(replace(uuid(),'-','')),'	JP',  'Japon', 0);
INSERT INTO T_COUNTRY (ID, CODE, NAME, CHECK_CANCEL)VALUES (unhex(replace(uuid(),'-','')),'	JO',  'Jordanie', 0);
INSERT INTO T_COUNTRY (ID, CODE, NAME, CHECK_CANCEL)VALUES (unhex(replace(uuid(),'-','')),'	KZ',  'Kazakstan', 0);
INSERT INTO T_COUNTRY (ID, CODE, NAME, CHECK_CANCEL)VALUES (unhex(replace(uuid(),'-','')),'	KE',  'Kenya', 0);
INSERT INTO T_COUNTRY (ID, CODE, NAME, CHECK_CANCEL)VALUES (unhex(replace(uuid(),'-','')),'	KI',  'Kiribati', 0);
INSERT INTO T_COUNTRY (ID, CODE, NAME, CHECK_CANCEL)VALUES (unhex(replace(uuid(),'-','')),'	KP',  'Corée (République populaire démocratique du)', 0);
INSERT INTO T_COUNTRY (ID, CODE, NAME, CHECK_CANCEL)VALUES (unhex(replace(uuid(),'-','')),'	KR',  'Corée (République démocratique du)', 0);
INSERT INTO T_COUNTRY (ID, CODE, NAME, CHECK_CANCEL)VALUES (unhex(replace(uuid(),'-','')),'	KW',  'Koweït', 0);
INSERT INTO T_COUNTRY (ID, CODE, NAME, CHECK_CANCEL)VALUES (unhex(replace(uuid(),'-','')),'	KG',  'Kyrgyzstan', 0);
INSERT INTO T_COUNTRY (ID, CODE, NAME, CHECK_CANCEL)VALUES (unhex(replace(uuid(),'-','')),'	LA',  'Laos (République populaire démocratique du)', 0);
INSERT INTO T_COUNTRY (ID, CODE, NAME, CHECK_CANCEL)VALUES (unhex(replace(uuid(),'-','')),'	LV',  'Lettonie', 0);
INSERT INTO T_COUNTRY (ID, CODE, NAME, CHECK_CANCEL)VALUES (unhex(replace(uuid(),'-','')),'	LB',  'Liban', 0);
INSERT INTO T_COUNTRY (ID, CODE, NAME, CHECK_CANCEL)VALUES (unhex(replace(uuid(),'-','')),'	LS',  'Lesotho', 0);
INSERT INTO T_COUNTRY (ID, CODE, NAME, CHECK_CANCEL)VALUES (unhex(replace(uuid(),'-','')),'	LR',  'Libéria', 0);
INSERT INTO T_COUNTRY (ID, CODE, NAME, CHECK_CANCEL)VALUES (unhex(replace(uuid(),'-','')),'	LY',  'Libye (Jamahiriya Arabe Libyenne)', 0);
INSERT INTO T_COUNTRY (ID, CODE, NAME, CHECK_CANCEL)VALUES (unhex(replace(uuid(),'-','')),'	LI',  'Liechtenstein', 0);
INSERT INTO T_COUNTRY (ID, CODE, NAME, CHECK_CANCEL)VALUES (unhex(replace(uuid(),'-','')),'	LT',  'Lithuanie', 0);
INSERT INTO T_COUNTRY (ID, CODE, NAME, CHECK_CANCEL)VALUES (unhex(replace(uuid(),'-','')),'	LU',  'Luxembourg', 0);
INSERT INTO T_COUNTRY (ID, CODE, NAME, CHECK_CANCEL)VALUES (unhex(replace(uuid(),'-','')),'	MO',  'Macau', 0);
INSERT INTO T_COUNTRY (ID, CODE, NAME, CHECK_CANCEL)VALUES (unhex(replace(uuid(),'-','')),'	MK',  'Macédoine (ancienne République yougoslave de)', 0);
INSERT INTO T_COUNTRY (ID, CODE, NAME, CHECK_CANCEL)VALUES (unhex(replace(uuid(),'-','')),'	MG',  'Madagascar', 0);
INSERT INTO T_COUNTRY (ID, CODE, NAME, CHECK_CANCEL)VALUES (unhex(replace(uuid(),'-','')),'	MW',  'Malawi', 0);
INSERT INTO T_COUNTRY (ID, CODE, NAME, CHECK_CANCEL)VALUES (unhex(replace(uuid(),'-','')),'	MY',  'Malaysie', 0);
INSERT INTO T_COUNTRY (ID, CODE, NAME, CHECK_CANCEL)VALUES (unhex(replace(uuid(),'-','')),'	MV',  'Maldives', 0);
INSERT INTO T_COUNTRY (ID, CODE, NAME, CHECK_CANCEL)VALUES (unhex(replace(uuid(),'-','')),'	ML',  'Mali', 0);
INSERT INTO T_COUNTRY (ID, CODE, NAME, CHECK_CANCEL)VALUES (unhex(replace(uuid(),'-','')),'	MT',  'Malte', 0);
INSERT INTO T_COUNTRY (ID, CODE, NAME, CHECK_CANCEL)VALUES (unhex(replace(uuid(),'-','')),'	MH',  'Marshall (Îles)', 0);
INSERT INTO T_COUNTRY (ID, CODE, NAME, CHECK_CANCEL)VALUES (unhex(replace(uuid(),'-','')),'	MQ',  'Martinique', 0);
INSERT INTO T_COUNTRY (ID, CODE, NAME, CHECK_CANCEL)VALUES (unhex(replace(uuid(),'-','')),'	MR',  'Mauritanie', 0);
INSERT INTO T_COUNTRY (ID, CODE, NAME, CHECK_CANCEL)VALUES (unhex(replace(uuid(),'-','')),'	MU',  'Maurice', 0);
INSERT INTO T_COUNTRY (ID, CODE, NAME, CHECK_CANCEL)VALUES (unhex(replace(uuid(),'-','')),'	YT',  'Mayotte', 0);
INSERT INTO T_COUNTRY (ID, CODE, NAME, CHECK_CANCEL)VALUES (unhex(replace(uuid(),'-','')),'	MX',  'Mexique', 0);
INSERT INTO T_COUNTRY (ID, CODE, NAME, CHECK_CANCEL)VALUES (unhex(replace(uuid(),'-','')),'	FM',  'Micronésie (Etats fédérés de)', 0);
INSERT INTO T_COUNTRY (ID, CODE, NAME, CHECK_CANCEL)VALUES (unhex(replace(uuid(),'-','')),'	MD',  'Moldavie', 0);
INSERT INTO T_COUNTRY (ID, CODE, NAME, CHECK_CANCEL)VALUES (unhex(replace(uuid(),'-','')),'	MC',  'Monaco', 0);
INSERT INTO T_COUNTRY (ID, CODE, NAME, CHECK_CANCEL)VALUES (unhex(replace(uuid(),'-','')),'	MN',  'Mongolie', 0);
INSERT INTO T_COUNTRY (ID, CODE, NAME, CHECK_CANCEL)VALUES (unhex(replace(uuid(),'-','')),'	MS',  'Montserrat', 0);
INSERT INTO T_COUNTRY (ID, CODE, NAME, CHECK_CANCEL)VALUES (unhex(replace(uuid(),'-','')),'	MA',  'Maroc', 0);
INSERT INTO T_COUNTRY (ID, CODE, NAME, CHECK_CANCEL)VALUES (unhex(replace(uuid(),'-','')),'	MZ',  'Mozambique', 0);
INSERT INTO T_COUNTRY (ID, CODE, NAME, CHECK_CANCEL)VALUES (unhex(replace(uuid(),'-','')),'	MM',  'Myanmar', 0);
INSERT INTO T_COUNTRY (ID, CODE, NAME, CHECK_CANCEL)VALUES (unhex(replace(uuid(),'-','')),'	NA',  'Namibie', 0);
INSERT INTO T_COUNTRY (ID, CODE, NAME, CHECK_CANCEL)VALUES (unhex(replace(uuid(),'-','')),'	NR',  'Nauru', 0);
INSERT INTO T_COUNTRY (ID, CODE, NAME, CHECK_CANCEL)VALUES (unhex(replace(uuid(),'-','')),'	NP',  'Népal', 0);
INSERT INTO T_COUNTRY (ID, CODE, NAME, CHECK_CANCEL)VALUES (unhex(replace(uuid(),'-','')),'	NL',  'Pays-Bas', 0);
INSERT INTO T_COUNTRY (ID, CODE, NAME, CHECK_CANCEL)VALUES (unhex(replace(uuid(),'-','')),'	AN',  'Antilles néerlandaises', 0);
INSERT INTO T_COUNTRY (ID, CODE, NAME, CHECK_CANCEL)VALUES (unhex(replace(uuid(),'-','')),'	NC',  'Nouvelle-Calédonie', 0);
INSERT INTO T_COUNTRY (ID, CODE, NAME, CHECK_CANCEL)VALUES (unhex(replace(uuid(),'-','')),'	NZ',  'Nouvelle-Zélande', 0);
INSERT INTO T_COUNTRY (ID, CODE, NAME, CHECK_CANCEL)VALUES (unhex(replace(uuid(),'-','')),'	NI',  'Nicaragua', 0);
INSERT INTO T_COUNTRY (ID, CODE, NAME, CHECK_CANCEL)VALUES (unhex(replace(uuid(),'-','')),'	NE',  'Niger', 0);
INSERT INTO T_COUNTRY (ID, CODE, NAME, CHECK_CANCEL)VALUES (unhex(replace(uuid(),'-','')),'	NG',  'Nigéria', 0);
INSERT INTO T_COUNTRY (ID, CODE, NAME, CHECK_CANCEL)VALUES (unhex(replace(uuid(),'-','')),'	NU',  'Niue', 0);
INSERT INTO T_COUNTRY (ID, CODE, NAME, CHECK_CANCEL)VALUES (unhex(replace(uuid(),'-','')),'	NF',  'Norfolk (Île)', 0);
INSERT INTO T_COUNTRY (ID, CODE, NAME, CHECK_CANCEL)VALUES (unhex(replace(uuid(),'-','')),'	MP',  'Mariannes (Îles)', 0);
INSERT INTO T_COUNTRY (ID, CODE, NAME, CHECK_CANCEL)VALUES (unhex(replace(uuid(),'-','')),'	NO',  'Norvège', 0);
INSERT INTO T_COUNTRY (ID, CODE, NAME, CHECK_CANCEL)VALUES (unhex(replace(uuid(),'-','')),'	OM',  'Oman', 0);
INSERT INTO T_COUNTRY (ID, CODE, NAME, CHECK_CANCEL)VALUES (unhex(replace(uuid(),'-','')),'	PK',  'Pakistan', 0);
INSERT INTO T_COUNTRY (ID, CODE, NAME, CHECK_CANCEL)VALUES (unhex(replace(uuid(),'-','')),'	PW',  'Palau', 0);
INSERT INTO T_COUNTRY (ID, CODE, NAME, CHECK_CANCEL)VALUES (unhex(replace(uuid(),'-','')),'	PA',  'Panama', 0);
INSERT INTO T_COUNTRY (ID, CODE, NAME, CHECK_CANCEL)VALUES (unhex(replace(uuid(),'-','')),'	PG',  'Papouasie Nouvelle-Guinée', 0);
INSERT INTO T_COUNTRY (ID, CODE, NAME, CHECK_CANCEL)VALUES (unhex(replace(uuid(),'-','')),'	PY',  'Paraguay', 0);
INSERT INTO T_COUNTRY (ID, CODE, NAME, CHECK_CANCEL)VALUES (unhex(replace(uuid(),'-','')),'	PE',  'Pérou', 0);
INSERT INTO T_COUNTRY (ID, CODE, NAME, CHECK_CANCEL)VALUES (unhex(replace(uuid(),'-','')),'	PH',  'Philippines', 0);
INSERT INTO T_COUNTRY (ID, CODE, NAME, CHECK_CANCEL)VALUES (unhex(replace(uuid(),'-','')),'	PN',  'Pitcaïrn', 0);
INSERT INTO T_COUNTRY (ID, CODE, NAME, CHECK_CANCEL)VALUES (unhex(replace(uuid(),'-','')),'	PL',  'Pologne', 0);
INSERT INTO T_COUNTRY (ID, CODE, NAME, CHECK_CANCEL)VALUES (unhex(replace(uuid(),'-','')),'	PT',  'Portugal', 0);
INSERT INTO T_COUNTRY (ID, CODE, NAME, CHECK_CANCEL)VALUES (unhex(replace(uuid(),'-','')),'	PR',  'Porto Rico', 0);
INSERT INTO T_COUNTRY (ID, CODE, NAME, CHECK_CANCEL)VALUES (unhex(replace(uuid(),'-','')),'	QA',  'Quatar', 0);
INSERT INTO T_COUNTRY (ID, CODE, NAME, CHECK_CANCEL)VALUES (unhex(replace(uuid(),'-','')),'	RE',  'Réunion', 0);
INSERT INTO T_COUNTRY (ID, CODE, NAME, CHECK_CANCEL)VALUES (unhex(replace(uuid(),'-','')),'	RO',  'Romania', 0);
INSERT INTO T_COUNTRY (ID, CODE, NAME, CHECK_CANCEL)VALUES (unhex(replace(uuid(),'-','')),'	RU',  'Russie (Fédération de)', 0);
INSERT INTO T_COUNTRY (ID, CODE, NAME, CHECK_CANCEL)VALUES (unhex(replace(uuid(),'-','')),'	RW',  'Rwanda', 0);
INSERT INTO T_COUNTRY (ID, CODE, NAME, CHECK_CANCEL)VALUES (unhex(replace(uuid(),'-','')),'	KN',  'Saint Kitts et Nevis', 0);
INSERT INTO T_COUNTRY (ID, CODE, NAME, CHECK_CANCEL)VALUES (unhex(replace(uuid(),'-','')),'	LC',  'Sainte Lucie', 0);
INSERT INTO T_COUNTRY (ID, CODE, NAME, CHECK_CANCEL)VALUES (unhex(replace(uuid(),'-','')),'	VC',  'Saint Vincent et Grenadines', 0);
INSERT INTO T_COUNTRY (ID, CODE, NAME, CHECK_CANCEL)VALUES (unhex(replace(uuid(),'-','')),'	WS',  'Samoa', 0);
INSERT INTO T_COUNTRY (ID, CODE, NAME, CHECK_CANCEL)VALUES (unhex(replace(uuid(),'-','')),'	SM',  'San Marin', 0);
INSERT INTO T_COUNTRY (ID, CODE, NAME, CHECK_CANCEL)VALUES (unhex(replace(uuid(),'-','')),'	ST',  'Sao Tomé et Principe', 0);
INSERT INTO T_COUNTRY (ID, CODE, NAME, CHECK_CANCEL)VALUES (unhex(replace(uuid(),'-','')),'	SA',  'Arabie Séoudite', 0);
INSERT INTO T_COUNTRY (ID, CODE, NAME, CHECK_CANCEL)VALUES (unhex(replace(uuid(),'-','')),'	SN',  'Sénégal', 0);
INSERT INTO T_COUNTRY (ID, CODE, NAME, CHECK_CANCEL)VALUES (unhex(replace(uuid(),'-','')),'	SC',  'Seychelles', 0);
INSERT INTO T_COUNTRY (ID, CODE, NAME, CHECK_CANCEL)VALUES (unhex(replace(uuid(),'-','')),'	SL',  'Sierra Léone', 0);
INSERT INTO T_COUNTRY (ID, CODE, NAME, CHECK_CANCEL)VALUES (unhex(replace(uuid(),'-','')),'	SG',  'Singapour', 0);
INSERT INTO T_COUNTRY (ID, CODE, NAME, CHECK_CANCEL)VALUES (unhex(replace(uuid(),'-','')),'	SK',  'Slovaquie', 0);
INSERT INTO T_COUNTRY (ID, CODE, NAME, CHECK_CANCEL)VALUES (unhex(replace(uuid(),'-','')),'	SI',  'Slovénie', 0);
INSERT INTO T_COUNTRY (ID, CODE, NAME, CHECK_CANCEL)VALUES (unhex(replace(uuid(),'-','')),'	SB',  'Salomon (Îles)', 0);
INSERT INTO T_COUNTRY (ID, CODE, NAME, CHECK_CANCEL)VALUES (unhex(replace(uuid(),'-','')),'	SO',  'Somalie', 0);
INSERT INTO T_COUNTRY (ID, CODE, NAME, CHECK_CANCEL)VALUES (unhex(replace(uuid(),'-','')),'	ZA',  'Afrique du Sud', 0);
INSERT INTO T_COUNTRY (ID, CODE, NAME, CHECK_CANCEL)VALUES (unhex(replace(uuid(),'-','')),'	GS',  'Géorgie du Sud et îles Sandwich du Sud', 0);
INSERT INTO T_COUNTRY (ID, CODE, NAME, CHECK_CANCEL)VALUES (unhex(replace(uuid(),'-','')),'	ES',  'Espagne', 0);
INSERT INTO T_COUNTRY (ID, CODE, NAME, CHECK_CANCEL)VALUES (unhex(replace(uuid(),'-','')),'	LK',  'Sri Lanka', 0);
INSERT INTO T_COUNTRY (ID, CODE, NAME, CHECK_CANCEL)VALUES (unhex(replace(uuid(),'-','')),'	SH',  'Ste Hélène', 0);
INSERT INTO T_COUNTRY (ID, CODE, NAME, CHECK_CANCEL)VALUES (unhex(replace(uuid(),'-','')),'	PM',  'St. Pierre et Miquelon', 0);
INSERT INTO T_COUNTRY (ID, CODE, NAME, CHECK_CANCEL)VALUES (unhex(replace(uuid(),'-','')),'	SD',  'Soudan', 0);
INSERT INTO T_COUNTRY (ID, CODE, NAME, CHECK_CANCEL)VALUES (unhex(replace(uuid(),'-','')),'	SR',  'Surinam', 0);
INSERT INTO T_COUNTRY (ID, CODE, NAME, CHECK_CANCEL)VALUES (unhex(replace(uuid(),'-','')),'	SJ',  'Svalbard et Jan Mayen (Îles)', 0);
INSERT INTO T_COUNTRY (ID, CODE, NAME, CHECK_CANCEL)VALUES (unhex(replace(uuid(),'-','')),'	SZ',  'Swaziland', 0);
INSERT INTO T_COUNTRY (ID, CODE, NAME, CHECK_CANCEL)VALUES (unhex(replace(uuid(),'-','')),'	SE',  'Suède', 0);
INSERT INTO T_COUNTRY (ID, CODE, NAME, CHECK_CANCEL)VALUES (unhex(replace(uuid(),'-','')),'	CH',  'Suisse', 0);
INSERT INTO T_COUNTRY (ID, CODE, NAME, CHECK_CANCEL)VALUES (unhex(replace(uuid(),'-','')),'	SY',  'Syrie (République arabe syrienne)', 0);
INSERT INTO T_COUNTRY (ID, CODE, NAME, CHECK_CANCEL)VALUES (unhex(replace(uuid(),'-','')),'	TW',  'Taïwan', 0);
INSERT INTO T_COUNTRY (ID, CODE, NAME, CHECK_CANCEL)VALUES (unhex(replace(uuid(),'-','')),'	TJ',  'Tadjikistan', 0);
INSERT INTO T_COUNTRY (ID, CODE, NAME, CHECK_CANCEL)VALUES (unhex(replace(uuid(),'-','')),'	TZ',  'Tanzanie', 0);
INSERT INTO T_COUNTRY (ID, CODE, NAME, CHECK_CANCEL)VALUES (unhex(replace(uuid(),'-','')),'	TH',  'Thaïlande', 0);
INSERT INTO T_COUNTRY (ID, CODE, NAME, CHECK_CANCEL)VALUES (unhex(replace(uuid(),'-','')),'	TG',  'Togo', 0);
INSERT INTO T_COUNTRY (ID, CODE, NAME, CHECK_CANCEL)VALUES (unhex(replace(uuid(),'-','')),'	TK',  'Tokelau', 0);
INSERT INTO T_COUNTRY (ID, CODE, NAME, CHECK_CANCEL)VALUES (unhex(replace(uuid(),'-','')),'	TO',  'Tonga', 0);
INSERT INTO T_COUNTRY (ID, CODE, NAME, CHECK_CANCEL)VALUES (unhex(replace(uuid(),'-','')),'	TT',  'Trinidad et Tobago', 0);
INSERT INTO T_COUNTRY (ID, CODE, NAME, CHECK_CANCEL)VALUES (unhex(replace(uuid(),'-','')),'	TN',  'Tunisie', 0);
INSERT INTO T_COUNTRY (ID, CODE, NAME, CHECK_CANCEL)VALUES (unhex(replace(uuid(),'-','')),'	TR',  'Turquie', 0);
INSERT INTO T_COUNTRY (ID, CODE, NAME, CHECK_CANCEL)VALUES (unhex(replace(uuid(),'-','')),'	TM',  'Turkménistan', 0);
INSERT INTO T_COUNTRY (ID, CODE, NAME, CHECK_CANCEL)VALUES (unhex(replace(uuid(),'-','')),'	TC',  'Turks et Caicos (Îles)', 0);
INSERT INTO T_COUNTRY (ID, CODE, NAME, CHECK_CANCEL)VALUES (unhex(replace(uuid(),'-','')),'	TV',  'Tuvalu', 0);
INSERT INTO T_COUNTRY (ID, CODE, NAME, CHECK_CANCEL)VALUES (unhex(replace(uuid(),'-','')),'	UG',  'Ouganda', 0);
INSERT INTO T_COUNTRY (ID, CODE, NAME, CHECK_CANCEL)VALUES (unhex(replace(uuid(),'-','')),'	UA',  'Ukraine', 0);
INSERT INTO T_COUNTRY (ID, CODE, NAME, CHECK_CANCEL)VALUES (unhex(replace(uuid(),'-','')),'	AE',  'Emirats Arabes Unis', 0);
INSERT INTO T_COUNTRY (ID, CODE, NAME, CHECK_CANCEL)VALUES (unhex(replace(uuid(),'-','')),'	GB',  'Royaume-Uni', 0);
INSERT INTO T_COUNTRY (ID, CODE, NAME, CHECK_CANCEL)VALUES (unhex(replace(uuid(),'-','')),'	US',  'Etats-Unis d Amérique', 0);
INSERT INTO T_COUNTRY (ID, CODE, NAME, CHECK_CANCEL)VALUES (unhex(replace(uuid(),'-','')),'	UM',  'Territoires non incorporés des États-Unis ', 0);
INSERT INTO T_COUNTRY (ID, CODE, NAME, CHECK_CANCEL)VALUES (unhex(replace(uuid(),'-','')),'	UY',  'Uruguay', 0);
INSERT INTO T_COUNTRY (ID, CODE, NAME, CHECK_CANCEL)VALUES (unhex(replace(uuid(),'-','')),'	UZ',  'Ouzbékistan', 0);
INSERT INTO T_COUNTRY (ID, CODE, NAME, CHECK_CANCEL)VALUES (unhex(replace(uuid(),'-','')),'	VU',  'Vanuatu', 0);
INSERT INTO T_COUNTRY (ID, CODE, NAME, CHECK_CANCEL)VALUES (unhex(replace(uuid(),'-','')),'	VE',  'Vénézuela', 0);
INSERT INTO T_COUNTRY (ID, CODE, NAME, CHECK_CANCEL)VALUES (unhex(replace(uuid(),'-','')),'	VN',  'Vietnam', 0);
INSERT INTO T_COUNTRY (ID, CODE, NAME, CHECK_CANCEL)VALUES (unhex(replace(uuid(),'-','')),'	VG',  'Vierges (Îles) - RU', 0);
INSERT INTO T_COUNTRY (ID, CODE, NAME, CHECK_CANCEL)VALUES (unhex(replace(uuid(),'-','')),'	VI',  'Vierges (Îles) - EU', 0);
INSERT INTO T_COUNTRY (ID, CODE, NAME, CHECK_CANCEL)VALUES (unhex(replace(uuid(),'-','')),'	WF',  'Wallis et Futuna (Îles)', 0);
INSERT INTO T_COUNTRY (ID, CODE, NAME, CHECK_CANCEL)VALUES (unhex(replace(uuid(),'-','')),'	EH',  'Sahara Occidental', 0);
INSERT INTO T_COUNTRY (ID, CODE, NAME, CHECK_CANCEL)VALUES (unhex(replace(uuid(),'-','')),'	YE',  'Yemen', 0);
INSERT INTO T_COUNTRY (ID, CODE, NAME, CHECK_CANCEL)VALUES (unhex(replace(uuid(),'-','')),'	YU',  'Yougoslavie', 0);
INSERT INTO T_COUNTRY (ID, CODE, NAME, CHECK_CANCEL)VALUES (unhex(replace(uuid(),'-','')),'	ZM',  'Zambie', 0);
INSERT INTO T_COUNTRY (ID, CODE, NAME, CHECK_CANCEL)VALUES (unhex(replace(uuid(),'-','')),'	ZW',  'Zimbabwe', 0);