package com.oryx.remote.webservice.element._enum;

import javax.xml.namespace.QName;
import javax.xml.ws.*;
import java.net.MalformedURLException;
import java.net.URL;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.2.10
 * Generated source version: 2.2
 */
@WebServiceClient(name = "AuthenticationServices", targetNamespace = "http://enum.element.webservice.remote.oryx.com", wsdlLocation = "http://localhost:8680/oryx-server/AuthenticationService.wsdl")
public class AuthenticationServices
        extends Service {

    private final static URL AUTHENTICATIONSERVICES_WSDL_LOCATION;
    private final static WebServiceException AUTHENTICATIONSERVICES_EXCEPTION;
    private final static QName AUTHENTICATIONSERVICES_QNAME = new QName("http://enum.element.webservice.remote.oryx.com", "AuthenticationServices");

    static {
        URL url = null;
        WebServiceException e = null;
        try {
            url = new URL("http://localhost:8680/oryx-server/AuthenticationService.wsdl");
        } catch (MalformedURLException ex) {
            e = new WebServiceException(ex);
        }
        AUTHENTICATIONSERVICES_WSDL_LOCATION = url;
        AUTHENTICATIONSERVICES_EXCEPTION = e;
    }

    public AuthenticationServices() {
        super(__getWsdlLocation(), AUTHENTICATIONSERVICES_QNAME);
    }

    public AuthenticationServices(WebServiceFeature... features) {
        super(__getWsdlLocation(), AUTHENTICATIONSERVICES_QNAME, features);
    }

    public AuthenticationServices(URL wsdlLocation) {
        super(wsdlLocation, AUTHENTICATIONSERVICES_QNAME);
    }

    public AuthenticationServices(URL wsdlLocation, WebServiceFeature... features) {
        super(wsdlLocation, AUTHENTICATIONSERVICES_QNAME, features);
    }

    public AuthenticationServices(URL wsdlLocation, QName serviceName) {
        super(wsdlLocation, serviceName);
    }

    public AuthenticationServices(URL wsdlLocation, QName serviceName, WebServiceFeature... features) {
        super(wsdlLocation, serviceName, features);
    }

    private static URL __getWsdlLocation() {
        if (AUTHENTICATIONSERVICES_EXCEPTION != null) {
            throw AUTHENTICATIONSERVICES_EXCEPTION;
        }
        return AUTHENTICATIONSERVICES_WSDL_LOCATION;
    }

    /**
     * @return returns AuthenticationService
     */
    @WebEndpoint(name = "AuthenticationServiceSoap11")
    public AuthenticationService getAuthenticationServiceSoap11() {
        return super.getPort(new QName("http://enum.element.webservice.remote.oryx.com", "AuthenticationServiceSoap11"), AuthenticationService.class);
    }

    /**
     * @param features A list of {@link javax.xml.ws.WebServiceFeature} to configure on the proxy.  Supported features not in the <code>features</code> parameter will have their default values.
     * @return returns AuthenticationService
     */
    @WebEndpoint(name = "AuthenticationServiceSoap11")
    public AuthenticationService getAuthenticationServiceSoap11(WebServiceFeature... features) {
        return super.getPort(new QName("http://enum.element.webservice.remote.oryx.com", "AuthenticationServiceSoap11"), AuthenticationService.class, features);
    }

}
