package com.oryx.remote.webservice.element._enum;

import javax.xml.namespace.QName;
import javax.xml.ws.*;
import java.net.MalformedURLException;
import java.net.URL;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.2.10
 * Generated source version: 2.2
 */
@WebServiceClient(name = "BillItemServices", targetNamespace = "http://enum.element.webservice.remote.oryx.com", wsdlLocation = "http://localhost:8680/oryx-server/BillItemService.wsdl")
public class BillItemServices
        extends Service {

    private final static URL BILLITEMSERVICES_WSDL_LOCATION;
    private final static WebServiceException BILLITEMSERVICES_EXCEPTION;
    private final static QName BILLITEMSERVICES_QNAME = new QName("http://enum.element.webservice.remote.oryx.com", "BillItemServices");

    static {
        URL url = null;
        WebServiceException e = null;
        try {
            url = new URL("http://localhost:8680/oryx-server/BillItemService.wsdl");
        } catch (MalformedURLException ex) {
            e = new WebServiceException(ex);
        }
        BILLITEMSERVICES_WSDL_LOCATION = url;
        BILLITEMSERVICES_EXCEPTION = e;
    }

    public BillItemServices() {
        super(__getWsdlLocation(), BILLITEMSERVICES_QNAME);
    }

    public BillItemServices(WebServiceFeature... features) {
        super(__getWsdlLocation(), BILLITEMSERVICES_QNAME, features);
    }

    public BillItemServices(URL wsdlLocation) {
        super(wsdlLocation, BILLITEMSERVICES_QNAME);
    }

    public BillItemServices(URL wsdlLocation, WebServiceFeature... features) {
        super(wsdlLocation, BILLITEMSERVICES_QNAME, features);
    }

    public BillItemServices(URL wsdlLocation, QName serviceName) {
        super(wsdlLocation, serviceName);
    }

    public BillItemServices(URL wsdlLocation, QName serviceName, WebServiceFeature... features) {
        super(wsdlLocation, serviceName, features);
    }

    private static URL __getWsdlLocation() {
        if (BILLITEMSERVICES_EXCEPTION != null) {
            throw BILLITEMSERVICES_EXCEPTION;
        }
        return BILLITEMSERVICES_WSDL_LOCATION;
    }

    /**
     * @return returns BillItemService
     */
    @WebEndpoint(name = "BillItemServiceSoap11")
    public BillItemService getBillItemServiceSoap11() {
        return super.getPort(new QName("http://enum.element.webservice.remote.oryx.com", "BillItemServiceSoap11"), BillItemService.class);
    }

    /**
     * @param features A list of {@link javax.xml.ws.WebServiceFeature} to configure on the proxy.  Supported features not in the <code>features</code> parameter will have their default values.
     * @return returns BillItemService
     */
    @WebEndpoint(name = "BillItemServiceSoap11")
    public BillItemService getBillItemServiceSoap11(WebServiceFeature... features) {
        return super.getPort(new QName("http://enum.element.webservice.remote.oryx.com", "BillItemServiceSoap11"), BillItemService.class, features);
    }

}
