package com.oryx.remote.webservice.element._enum;

import javax.xml.namespace.QName;
import javax.xml.ws.*;
import java.net.MalformedURLException;
import java.net.URL;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.2.10
 * Generated source version: 2.2
 */
@WebServiceClient(name = "CartItemServices", targetNamespace = "http://enum.element.webservice.remote.oryx.com", wsdlLocation = "http://localhost:8680/oryx-server/CartItemService.wsdl")
public class CartItemServices
        extends Service {

    private final static URL CARTITEMSERVICES_WSDL_LOCATION;
    private final static WebServiceException CARTITEMSERVICES_EXCEPTION;
    private final static QName CARTITEMSERVICES_QNAME = new QName("http://enum.element.webservice.remote.oryx.com", "CartItemServices");

    static {
        URL url = null;
        WebServiceException e = null;
        try {
            url = new URL("http://localhost:8680/oryx-server/CartItemService.wsdl");
        } catch (MalformedURLException ex) {
            e = new WebServiceException(ex);
        }
        CARTITEMSERVICES_WSDL_LOCATION = url;
        CARTITEMSERVICES_EXCEPTION = e;
    }

    public CartItemServices() {
        super(__getWsdlLocation(), CARTITEMSERVICES_QNAME);
    }

    public CartItemServices(WebServiceFeature... features) {
        super(__getWsdlLocation(), CARTITEMSERVICES_QNAME, features);
    }

    public CartItemServices(URL wsdlLocation) {
        super(wsdlLocation, CARTITEMSERVICES_QNAME);
    }

    public CartItemServices(URL wsdlLocation, WebServiceFeature... features) {
        super(wsdlLocation, CARTITEMSERVICES_QNAME, features);
    }

    public CartItemServices(URL wsdlLocation, QName serviceName) {
        super(wsdlLocation, serviceName);
    }

    public CartItemServices(URL wsdlLocation, QName serviceName, WebServiceFeature... features) {
        super(wsdlLocation, serviceName, features);
    }

    private static URL __getWsdlLocation() {
        if (CARTITEMSERVICES_EXCEPTION != null) {
            throw CARTITEMSERVICES_EXCEPTION;
        }
        return CARTITEMSERVICES_WSDL_LOCATION;
    }

    /**
     * @return returns CartItemService
     */
    @WebEndpoint(name = "CartItemServiceSoap11")
    public CartItemService getCartItemServiceSoap11() {
        return super.getPort(new QName("http://enum.element.webservice.remote.oryx.com", "CartItemServiceSoap11"), CartItemService.class);
    }

    /**
     * @param features A list of {@link javax.xml.ws.WebServiceFeature} to configure on the proxy.  Supported features not in the <code>features</code> parameter will have their default values.
     * @return returns CartItemService
     */
    @WebEndpoint(name = "CartItemServiceSoap11")
    public CartItemService getCartItemServiceSoap11(WebServiceFeature... features) {
        return super.getPort(new QName("http://enum.element.webservice.remote.oryx.com", "CartItemServiceSoap11"), CartItemService.class, features);
    }

}
