package com.oryx.remote.webservice.element._enum;

import javax.xml.namespace.QName;
import javax.xml.ws.*;
import java.net.MalformedURLException;
import java.net.URL;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.2.10
 * Generated source version: 2.2
 */
@WebServiceClient(name = "CartServices", targetNamespace = "http://enum.element.webservice.remote.oryx.com", wsdlLocation = "http://localhost:8680/oryx-server/CartService.wsdl")
public class CartServices
        extends Service {

    private final static URL CARTSERVICES_WSDL_LOCATION;
    private final static WebServiceException CARTSERVICES_EXCEPTION;
    private final static QName CARTSERVICES_QNAME = new QName("http://enum.element.webservice.remote.oryx.com", "CartServices");

    static {
        URL url = null;
        WebServiceException e = null;
        try {
            url = new URL("http://localhost:8680/oryx-server/CartService.wsdl");
        } catch (MalformedURLException ex) {
            e = new WebServiceException(ex);
        }
        CARTSERVICES_WSDL_LOCATION = url;
        CARTSERVICES_EXCEPTION = e;
    }

    public CartServices() {
        super(__getWsdlLocation(), CARTSERVICES_QNAME);
    }

    public CartServices(WebServiceFeature... features) {
        super(__getWsdlLocation(), CARTSERVICES_QNAME, features);
    }

    public CartServices(URL wsdlLocation) {
        super(wsdlLocation, CARTSERVICES_QNAME);
    }

    public CartServices(URL wsdlLocation, WebServiceFeature... features) {
        super(wsdlLocation, CARTSERVICES_QNAME, features);
    }

    public CartServices(URL wsdlLocation, QName serviceName) {
        super(wsdlLocation, serviceName);
    }

    public CartServices(URL wsdlLocation, QName serviceName, WebServiceFeature... features) {
        super(wsdlLocation, serviceName, features);
    }

    private static URL __getWsdlLocation() {
        if (CARTSERVICES_EXCEPTION != null) {
            throw CARTSERVICES_EXCEPTION;
        }
        return CARTSERVICES_WSDL_LOCATION;
    }

    /**
     * @return returns CartService
     */
    @WebEndpoint(name = "CartServiceSoap11")
    public CartService getCartServiceSoap11() {
        return super.getPort(new QName("http://enum.element.webservice.remote.oryx.com", "CartServiceSoap11"), CartService.class);
    }

    /**
     * @param features A list of {@link javax.xml.ws.WebServiceFeature} to configure on the proxy.  Supported features not in the <code>features</code> parameter will have their default values.
     * @return returns CartService
     */
    @WebEndpoint(name = "CartServiceSoap11")
    public CartService getCartServiceSoap11(WebServiceFeature... features) {
        return super.getPort(new QName("http://enum.element.webservice.remote.oryx.com", "CartServiceSoap11"), CartService.class, features);
    }

}
