package com.oryx.remote.webservice.element._enum;

import javax.xml.namespace.QName;
import javax.xml.ws.*;
import java.net.MalformedURLException;
import java.net.URL;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.2.10
 * Generated source version: 2.2
 */
@WebServiceClient(name = "ErrorMessageServices", targetNamespace = "http://enum.element.webservice.remote.oryx.com", wsdlLocation = "http://localhost:8680/oryx-server/ErrorMessageService.wsdl")
public class ErrorMessageServices
        extends Service {

    private final static URL ERRORMESSAGESERVICES_WSDL_LOCATION;
    private final static WebServiceException ERRORMESSAGESERVICES_EXCEPTION;
    private final static QName ERRORMESSAGESERVICES_QNAME = new QName("http://enum.element.webservice.remote.oryx.com", "ErrorMessageServices");

    static {
        URL url = null;
        WebServiceException e = null;
        try {
            url = new URL("http://localhost:8680/oryx-server/ErrorMessageService.wsdl");
        } catch (MalformedURLException ex) {
            e = new WebServiceException(ex);
        }
        ERRORMESSAGESERVICES_WSDL_LOCATION = url;
        ERRORMESSAGESERVICES_EXCEPTION = e;
    }

    public ErrorMessageServices() {
        super(__getWsdlLocation(), ERRORMESSAGESERVICES_QNAME);
    }

    public ErrorMessageServices(WebServiceFeature... features) {
        super(__getWsdlLocation(), ERRORMESSAGESERVICES_QNAME, features);
    }

    public ErrorMessageServices(URL wsdlLocation) {
        super(wsdlLocation, ERRORMESSAGESERVICES_QNAME);
    }

    public ErrorMessageServices(URL wsdlLocation, WebServiceFeature... features) {
        super(wsdlLocation, ERRORMESSAGESERVICES_QNAME, features);
    }

    public ErrorMessageServices(URL wsdlLocation, QName serviceName) {
        super(wsdlLocation, serviceName);
    }

    public ErrorMessageServices(URL wsdlLocation, QName serviceName, WebServiceFeature... features) {
        super(wsdlLocation, serviceName, features);
    }

    private static URL __getWsdlLocation() {
        if (ERRORMESSAGESERVICES_EXCEPTION != null) {
            throw ERRORMESSAGESERVICES_EXCEPTION;
        }
        return ERRORMESSAGESERVICES_WSDL_LOCATION;
    }

    /**
     * @return returns ErrorMessageService
     */
    @WebEndpoint(name = "ErrorMessageServiceSoap11")
    public ErrorMessageService getErrorMessageServiceSoap11() {
        return super.getPort(new QName("http://enum.element.webservice.remote.oryx.com", "ErrorMessageServiceSoap11"), ErrorMessageService.class);
    }

    /**
     * @param features A list of {@link javax.xml.ws.WebServiceFeature} to configure on the proxy.  Supported features not in the <code>features</code> parameter will have their default values.
     * @return returns ErrorMessageService
     */
    @WebEndpoint(name = "ErrorMessageServiceSoap11")
    public ErrorMessageService getErrorMessageServiceSoap11(WebServiceFeature... features) {
        return super.getPort(new QName("http://enum.element.webservice.remote.oryx.com", "ErrorMessageServiceSoap11"), ErrorMessageService.class, features);
    }

}
