package com.oryx.remote.webservice.element._enum;

import javax.xml.namespace.QName;
import javax.xml.ws.*;
import java.net.MalformedURLException;
import java.net.URL;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.2.10
 * Generated source version: 2.2
 */
@WebServiceClient(name = "MenuServices", targetNamespace = "http://enum.element.webservice.remote.oryx.com", wsdlLocation = "http://localhost:8680/oryx-server/MenuService.wsdl")
public class MenuServices
        extends Service {

    private final static URL MENUSERVICES_WSDL_LOCATION;
    private final static WebServiceException MENUSERVICES_EXCEPTION;
    private final static QName MENUSERVICES_QNAME = new QName("http://enum.element.webservice.remote.oryx.com", "MenuServices");

    static {
        URL url = null;
        WebServiceException e = null;
        try {
            url = new URL("http://localhost:8680/oryx-server/MenuService.wsdl");
        } catch (MalformedURLException ex) {
            e = new WebServiceException(ex);
        }
        MENUSERVICES_WSDL_LOCATION = url;
        MENUSERVICES_EXCEPTION = e;
    }

    public MenuServices() {
        super(__getWsdlLocation(), MENUSERVICES_QNAME);
    }

    public MenuServices(WebServiceFeature... features) {
        super(__getWsdlLocation(), MENUSERVICES_QNAME, features);
    }

    public MenuServices(URL wsdlLocation) {
        super(wsdlLocation, MENUSERVICES_QNAME);
    }

    public MenuServices(URL wsdlLocation, WebServiceFeature... features) {
        super(wsdlLocation, MENUSERVICES_QNAME, features);
    }

    public MenuServices(URL wsdlLocation, QName serviceName) {
        super(wsdlLocation, serviceName);
    }

    public MenuServices(URL wsdlLocation, QName serviceName, WebServiceFeature... features) {
        super(wsdlLocation, serviceName, features);
    }

    private static URL __getWsdlLocation() {
        if (MENUSERVICES_EXCEPTION != null) {
            throw MENUSERVICES_EXCEPTION;
        }
        return MENUSERVICES_WSDL_LOCATION;
    }

    /**
     * @return returns MenuService
     */
    @WebEndpoint(name = "MenuServiceSoap11")
    public MenuService getMenuServiceSoap11() {
        return super.getPort(new QName("http://enum.element.webservice.remote.oryx.com", "MenuServiceSoap11"), MenuService.class);
    }

    /**
     * @param features A list of {@link javax.xml.ws.WebServiceFeature} to configure on the proxy.  Supported features not in the <code>features</code> parameter will have their default values.
     * @return returns MenuService
     */
    @WebEndpoint(name = "MenuServiceSoap11")
    public MenuService getMenuServiceSoap11(WebServiceFeature... features) {
        return super.getPort(new QName("http://enum.element.webservice.remote.oryx.com", "MenuServiceSoap11"), MenuService.class, features);
    }

}
