package com.oryx.remote.webservice.element._enum;

import javax.xml.namespace.QName;
import javax.xml.ws.*;
import java.net.MalformedURLException;
import java.net.URL;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.2.10
 * Generated source version: 2.2
 */
@WebServiceClient(name = "PersonServices", targetNamespace = "http://enum.element.webservice.remote.oryx.com", wsdlLocation = "http://localhost:8680/oryx-server/PersonService.wsdl")
public class PersonServices
        extends Service {

    private final static URL PERSONSERVICES_WSDL_LOCATION;
    private final static WebServiceException PERSONSERVICES_EXCEPTION;
    private final static QName PERSONSERVICES_QNAME = new QName("http://enum.element.webservice.remote.oryx.com", "PersonServices");

    static {
        URL url = null;
        WebServiceException e = null;
        try {
            url = new URL("http://localhost:8680/oryx-server/PersonService.wsdl");
        } catch (MalformedURLException ex) {
            e = new WebServiceException(ex);
        }
        PERSONSERVICES_WSDL_LOCATION = url;
        PERSONSERVICES_EXCEPTION = e;
    }

    public PersonServices() {
        super(__getWsdlLocation(), PERSONSERVICES_QNAME);
    }

    public PersonServices(WebServiceFeature... features) {
        super(__getWsdlLocation(), PERSONSERVICES_QNAME, features);
    }

    public PersonServices(URL wsdlLocation) {
        super(wsdlLocation, PERSONSERVICES_QNAME);
    }

    public PersonServices(URL wsdlLocation, WebServiceFeature... features) {
        super(wsdlLocation, PERSONSERVICES_QNAME, features);
    }

    public PersonServices(URL wsdlLocation, QName serviceName) {
        super(wsdlLocation, serviceName);
    }

    public PersonServices(URL wsdlLocation, QName serviceName, WebServiceFeature... features) {
        super(wsdlLocation, serviceName, features);
    }

    private static URL __getWsdlLocation() {
        if (PERSONSERVICES_EXCEPTION != null) {
            throw PERSONSERVICES_EXCEPTION;
        }
        return PERSONSERVICES_WSDL_LOCATION;
    }

    /**
     * @return returns PersonService
     */
    @WebEndpoint(name = "PersonServiceSoap11")
    public PersonService getPersonServiceSoap11() {
        return super.getPort(new QName("http://enum.element.webservice.remote.oryx.com", "PersonServiceSoap11"), PersonService.class);
    }

    /**
     * @param features A list of {@link javax.xml.ws.WebServiceFeature} to configure on the proxy.  Supported features not in the <code>features</code> parameter will have their default values.
     * @return returns PersonService
     */
    @WebEndpoint(name = "PersonServiceSoap11")
    public PersonService getPersonServiceSoap11(WebServiceFeature... features) {
        return super.getPort(new QName("http://enum.element.webservice.remote.oryx.com", "PersonServiceSoap11"), PersonService.class, features);
    }

}
