package com.oryx.remote.webservice.element._enum;

import javax.xml.namespace.QName;
import javax.xml.ws.*;
import java.net.MalformedURLException;
import java.net.URL;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.2.10
 * Generated source version: 2.2
 */
@WebServiceClient(name = "ProductLotServices", targetNamespace = "http://enum.element.webservice.remote.oryx.com", wsdlLocation = "http://localhost:8680/oryx-server/ProductLotService.wsdl")
public class ProductLotServices
        extends Service {

    private final static URL PRODUCTLOTSERVICES_WSDL_LOCATION;
    private final static WebServiceException PRODUCTLOTSERVICES_EXCEPTION;
    private final static QName PRODUCTLOTSERVICES_QNAME = new QName("http://enum.element.webservice.remote.oryx.com", "ProductLotServices");

    static {
        URL url = null;
        WebServiceException e = null;
        try {
            url = new URL("http://localhost:8680/oryx-server/ProductLotService.wsdl");
        } catch (MalformedURLException ex) {
            e = new WebServiceException(ex);
        }
        PRODUCTLOTSERVICES_WSDL_LOCATION = url;
        PRODUCTLOTSERVICES_EXCEPTION = e;
    }

    public ProductLotServices() {
        super(__getWsdlLocation(), PRODUCTLOTSERVICES_QNAME);
    }

    public ProductLotServices(WebServiceFeature... features) {
        super(__getWsdlLocation(), PRODUCTLOTSERVICES_QNAME, features);
    }

    public ProductLotServices(URL wsdlLocation) {
        super(wsdlLocation, PRODUCTLOTSERVICES_QNAME);
    }

    public ProductLotServices(URL wsdlLocation, WebServiceFeature... features) {
        super(wsdlLocation, PRODUCTLOTSERVICES_QNAME, features);
    }

    public ProductLotServices(URL wsdlLocation, QName serviceName) {
        super(wsdlLocation, serviceName);
    }

    public ProductLotServices(URL wsdlLocation, QName serviceName, WebServiceFeature... features) {
        super(wsdlLocation, serviceName, features);
    }

    private static URL __getWsdlLocation() {
        if (PRODUCTLOTSERVICES_EXCEPTION != null) {
            throw PRODUCTLOTSERVICES_EXCEPTION;
        }
        return PRODUCTLOTSERVICES_WSDL_LOCATION;
    }

    /**
     * @return returns ProductLotService
     */
    @WebEndpoint(name = "ProductLotServiceSoap11")
    public ProductLotService getProductLotServiceSoap11() {
        return super.getPort(new QName("http://enum.element.webservice.remote.oryx.com", "ProductLotServiceSoap11"), ProductLotService.class);
    }

    /**
     * @param features A list of {@link javax.xml.ws.WebServiceFeature} to configure on the proxy.  Supported features not in the <code>features</code> parameter will have their default values.
     * @return returns ProductLotService
     */
    @WebEndpoint(name = "ProductLotServiceSoap11")
    public ProductLotService getProductLotServiceSoap11(WebServiceFeature... features) {
        return super.getPort(new QName("http://enum.element.webservice.remote.oryx.com", "ProductLotServiceSoap11"), ProductLotService.class, features);
    }

}
