package com.oryx.remote.webservice.element._enum;

import javax.xml.namespace.QName;
import javax.xml.ws.*;
import java.net.MalformedURLException;
import java.net.URL;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.2.10
 * Generated source version: 2.2
 */
@WebServiceClient(name = "RdvServices", targetNamespace = "http://enum.element.webservice.remote.oryx.com", wsdlLocation = "http://localhost:8680/oryx-server/RdvService.wsdl")
public class RdvServices
        extends Service {

    private final static URL RDVSERVICES_WSDL_LOCATION;
    private final static WebServiceException RDVSERVICES_EXCEPTION;
    private final static QName RDVSERVICES_QNAME = new QName("http://enum.element.webservice.remote.oryx.com", "RdvServices");

    static {
        URL url = null;
        WebServiceException e = null;
        try {
            url = new URL("http://localhost:8680/oryx-server/RdvService.wsdl");
        } catch (MalformedURLException ex) {
            e = new WebServiceException(ex);
        }
        RDVSERVICES_WSDL_LOCATION = url;
        RDVSERVICES_EXCEPTION = e;
    }

    public RdvServices() {
        super(__getWsdlLocation(), RDVSERVICES_QNAME);
    }

    public RdvServices(WebServiceFeature... features) {
        super(__getWsdlLocation(), RDVSERVICES_QNAME, features);
    }

    public RdvServices(URL wsdlLocation) {
        super(wsdlLocation, RDVSERVICES_QNAME);
    }

    public RdvServices(URL wsdlLocation, WebServiceFeature... features) {
        super(wsdlLocation, RDVSERVICES_QNAME, features);
    }

    public RdvServices(URL wsdlLocation, QName serviceName) {
        super(wsdlLocation, serviceName);
    }

    public RdvServices(URL wsdlLocation, QName serviceName, WebServiceFeature... features) {
        super(wsdlLocation, serviceName, features);
    }

    private static URL __getWsdlLocation() {
        if (RDVSERVICES_EXCEPTION != null) {
            throw RDVSERVICES_EXCEPTION;
        }
        return RDVSERVICES_WSDL_LOCATION;
    }

    /**
     * @return returns RdvService
     */
    @WebEndpoint(name = "RdvServiceSoap11")
    public RdvService getRdvServiceSoap11() {
        return super.getPort(new QName("http://enum.element.webservice.remote.oryx.com", "RdvServiceSoap11"), RdvService.class);
    }

    /**
     * @param features A list of {@link javax.xml.ws.WebServiceFeature} to configure on the proxy.  Supported features not in the <code>features</code> parameter will have their default values.
     * @return returns RdvService
     */
    @WebEndpoint(name = "RdvServiceSoap11")
    public RdvService getRdvServiceSoap11(WebServiceFeature... features) {
        return super.getPort(new QName("http://enum.element.webservice.remote.oryx.com", "RdvServiceSoap11"), RdvService.class, features);
    }

}
