package com.oryx.remote.webservice.element._enum;

import javax.xml.namespace.QName;
import javax.xml.ws.*;
import java.net.MalformedURLException;
import java.net.URL;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.2.10
 * Generated source version: 2.2
 */
@WebServiceClient(name = "RoleInfoServices", targetNamespace = "http://enum.element.webservice.remote.oryx.com", wsdlLocation = "http://localhost:8680/oryx-server/RoleInfoService.wsdl")
public class RoleInfoServices
        extends Service {

    private final static URL ROLEINFOSERVICES_WSDL_LOCATION;
    private final static WebServiceException ROLEINFOSERVICES_EXCEPTION;
    private final static QName ROLEINFOSERVICES_QNAME = new QName("http://enum.element.webservice.remote.oryx.com", "RoleInfoServices");

    static {
        URL url = null;
        WebServiceException e = null;
        try {
            url = new URL("http://localhost:8680/oryx-server/RoleInfoService.wsdl");
        } catch (MalformedURLException ex) {
            e = new WebServiceException(ex);
        }
        ROLEINFOSERVICES_WSDL_LOCATION = url;
        ROLEINFOSERVICES_EXCEPTION = e;
    }

    public RoleInfoServices() {
        super(__getWsdlLocation(), ROLEINFOSERVICES_QNAME);
    }

    public RoleInfoServices(WebServiceFeature... features) {
        super(__getWsdlLocation(), ROLEINFOSERVICES_QNAME, features);
    }

    public RoleInfoServices(URL wsdlLocation) {
        super(wsdlLocation, ROLEINFOSERVICES_QNAME);
    }

    public RoleInfoServices(URL wsdlLocation, WebServiceFeature... features) {
        super(wsdlLocation, ROLEINFOSERVICES_QNAME, features);
    }

    public RoleInfoServices(URL wsdlLocation, QName serviceName) {
        super(wsdlLocation, serviceName);
    }

    public RoleInfoServices(URL wsdlLocation, QName serviceName, WebServiceFeature... features) {
        super(wsdlLocation, serviceName, features);
    }

    private static URL __getWsdlLocation() {
        if (ROLEINFOSERVICES_EXCEPTION != null) {
            throw ROLEINFOSERVICES_EXCEPTION;
        }
        return ROLEINFOSERVICES_WSDL_LOCATION;
    }

    /**
     * @return returns RoleInfoService
     */
    @WebEndpoint(name = "RoleInfoServiceSoap11")
    public RoleInfoService getRoleInfoServiceSoap11() {
        return super.getPort(new QName("http://enum.element.webservice.remote.oryx.com", "RoleInfoServiceSoap11"), RoleInfoService.class);
    }

    /**
     * @param features A list of {@link javax.xml.ws.WebServiceFeature} to configure on the proxy.  Supported features not in the <code>features</code> parameter will have their default values.
     * @return returns RoleInfoService
     */
    @WebEndpoint(name = "RoleInfoServiceSoap11")
    public RoleInfoService getRoleInfoServiceSoap11(WebServiceFeature... features) {
        return super.getPort(new QName("http://enum.element.webservice.remote.oryx.com", "RoleInfoServiceSoap11"), RoleInfoService.class, features);
    }

}
