package com.oryx.remote.webservice.element._enum;

import javax.xml.namespace.QName;
import javax.xml.ws.*;
import java.net.MalformedURLException;
import java.net.URL;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.2.10
 * Generated source version: 2.2
 */
@WebServiceClient(name = "StateServices", targetNamespace = "http://enum.element.webservice.remote.oryx.com", wsdlLocation = "http://localhost:8680/oryx-server/StateService.wsdl")
public class StateServices
        extends Service {

    private final static URL STATESERVICES_WSDL_LOCATION;
    private final static WebServiceException STATESERVICES_EXCEPTION;
    private final static QName STATESERVICES_QNAME = new QName("http://enum.element.webservice.remote.oryx.com", "StateServices");

    static {
        URL url = null;
        WebServiceException e = null;
        try {
            url = new URL("http://localhost:8680/oryx-server/StateService.wsdl");
        } catch (MalformedURLException ex) {
            e = new WebServiceException(ex);
        }
        STATESERVICES_WSDL_LOCATION = url;
        STATESERVICES_EXCEPTION = e;
    }

    public StateServices() {
        super(__getWsdlLocation(), STATESERVICES_QNAME);
    }

    public StateServices(WebServiceFeature... features) {
        super(__getWsdlLocation(), STATESERVICES_QNAME, features);
    }

    public StateServices(URL wsdlLocation) {
        super(wsdlLocation, STATESERVICES_QNAME);
    }

    public StateServices(URL wsdlLocation, WebServiceFeature... features) {
        super(wsdlLocation, STATESERVICES_QNAME, features);
    }

    public StateServices(URL wsdlLocation, QName serviceName) {
        super(wsdlLocation, serviceName);
    }

    public StateServices(URL wsdlLocation, QName serviceName, WebServiceFeature... features) {
        super(wsdlLocation, serviceName, features);
    }

    private static URL __getWsdlLocation() {
        if (STATESERVICES_EXCEPTION != null) {
            throw STATESERVICES_EXCEPTION;
        }
        return STATESERVICES_WSDL_LOCATION;
    }

    /**
     * @return returns StateService
     */
    @WebEndpoint(name = "StateServiceSoap11")
    public StateService getStateServiceSoap11() {
        return super.getPort(new QName("http://enum.element.webservice.remote.oryx.com", "StateServiceSoap11"), StateService.class);
    }

    /**
     * @param features A list of {@link javax.xml.ws.WebServiceFeature} to configure on the proxy.  Supported features not in the <code>features</code> parameter will have their default values.
     * @return returns StateService
     */
    @WebEndpoint(name = "StateServiceSoap11")
    public StateService getStateServiceSoap11(WebServiceFeature... features) {
        return super.getPort(new QName("http://enum.element.webservice.remote.oryx.com", "StateServiceSoap11"), StateService.class, features);
    }

}
