package com.oryx.remote.webservice.element._enum;

import javax.xml.namespace.QName;
import javax.xml.ws.*;
import java.net.MalformedURLException;
import java.net.URL;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.2.10
 * Generated source version: 2.2
 */
@WebServiceClient(name = "StockPositionServices", targetNamespace = "http://enum.element.webservice.remote.oryx.com", wsdlLocation = "http://localhost:8680/oryx-server/StockPositionService.wsdl")
public class StockPositionServices
        extends Service {

    private final static URL STOCKPOSITIONSERVICES_WSDL_LOCATION;
    private final static WebServiceException STOCKPOSITIONSERVICES_EXCEPTION;
    private final static QName STOCKPOSITIONSERVICES_QNAME = new QName("http://enum.element.webservice.remote.oryx.com", "StockPositionServices");

    static {
        URL url = null;
        WebServiceException e = null;
        try {
            url = new URL("http://localhost:8680/oryx-server/StockPositionService.wsdl");
        } catch (MalformedURLException ex) {
            e = new WebServiceException(ex);
        }
        STOCKPOSITIONSERVICES_WSDL_LOCATION = url;
        STOCKPOSITIONSERVICES_EXCEPTION = e;
    }

    public StockPositionServices() {
        super(__getWsdlLocation(), STOCKPOSITIONSERVICES_QNAME);
    }

    public StockPositionServices(WebServiceFeature... features) {
        super(__getWsdlLocation(), STOCKPOSITIONSERVICES_QNAME, features);
    }

    public StockPositionServices(URL wsdlLocation) {
        super(wsdlLocation, STOCKPOSITIONSERVICES_QNAME);
    }

    public StockPositionServices(URL wsdlLocation, WebServiceFeature... features) {
        super(wsdlLocation, STOCKPOSITIONSERVICES_QNAME, features);
    }

    public StockPositionServices(URL wsdlLocation, QName serviceName) {
        super(wsdlLocation, serviceName);
    }

    public StockPositionServices(URL wsdlLocation, QName serviceName, WebServiceFeature... features) {
        super(wsdlLocation, serviceName, features);
    }

    private static URL __getWsdlLocation() {
        if (STOCKPOSITIONSERVICES_EXCEPTION != null) {
            throw STOCKPOSITIONSERVICES_EXCEPTION;
        }
        return STOCKPOSITIONSERVICES_WSDL_LOCATION;
    }

    /**
     * @return returns StockPositionService
     */
    @WebEndpoint(name = "StockPositionServiceSoap11")
    public StockPositionService getStockPositionServiceSoap11() {
        return super.getPort(new QName("http://enum.element.webservice.remote.oryx.com", "StockPositionServiceSoap11"), StockPositionService.class);
    }

    /**
     * @param features A list of {@link javax.xml.ws.WebServiceFeature} to configure on the proxy.  Supported features not in the <code>features</code> parameter will have their default values.
     * @return returns StockPositionService
     */
    @WebEndpoint(name = "StockPositionServiceSoap11")
    public StockPositionService getStockPositionServiceSoap11(WebServiceFeature... features) {
        return super.getPort(new QName("http://enum.element.webservice.remote.oryx.com", "StockPositionServiceSoap11"), StockPositionService.class, features);
    }

}
