package com.oryx.remote.webservice.element._enum;

import javax.xml.namespace.QName;
import javax.xml.ws.*;
import java.net.MalformedURLException;
import java.net.URL;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.2.10
 * Generated source version: 2.2
 */
@WebServiceClient(name = "TaskServices", targetNamespace = "http://enum.element.webservice.remote.oryx.com", wsdlLocation = "http://localhost:8680/oryx-server/TaskService.wsdl")
public class TaskServices
        extends Service {

    private final static URL TASKSERVICES_WSDL_LOCATION;
    private final static WebServiceException TASKSERVICES_EXCEPTION;
    private final static QName TASKSERVICES_QNAME = new QName("http://enum.element.webservice.remote.oryx.com", "TaskServices");

    static {
        URL url = null;
        WebServiceException e = null;
        try {
            url = new URL("http://localhost:8680/oryx-server/TaskService.wsdl");
        } catch (MalformedURLException ex) {
            e = new WebServiceException(ex);
        }
        TASKSERVICES_WSDL_LOCATION = url;
        TASKSERVICES_EXCEPTION = e;
    }

    public TaskServices() {
        super(__getWsdlLocation(), TASKSERVICES_QNAME);
    }

    public TaskServices(WebServiceFeature... features) {
        super(__getWsdlLocation(), TASKSERVICES_QNAME, features);
    }

    public TaskServices(URL wsdlLocation) {
        super(wsdlLocation, TASKSERVICES_QNAME);
    }

    public TaskServices(URL wsdlLocation, WebServiceFeature... features) {
        super(wsdlLocation, TASKSERVICES_QNAME, features);
    }

    public TaskServices(URL wsdlLocation, QName serviceName) {
        super(wsdlLocation, serviceName);
    }

    public TaskServices(URL wsdlLocation, QName serviceName, WebServiceFeature... features) {
        super(wsdlLocation, serviceName, features);
    }

    private static URL __getWsdlLocation() {
        if (TASKSERVICES_EXCEPTION != null) {
            throw TASKSERVICES_EXCEPTION;
        }
        return TASKSERVICES_WSDL_LOCATION;
    }

    /**
     * @return returns TaskService
     */
    @WebEndpoint(name = "TaskServiceSoap11")
    public TaskService getTaskServiceSoap11() {
        return super.getPort(new QName("http://enum.element.webservice.remote.oryx.com", "TaskServiceSoap11"), TaskService.class);
    }

    /**
     * @param features A list of {@link javax.xml.ws.WebServiceFeature} to configure on the proxy.  Supported features not in the <code>features</code> parameter will have their default values.
     * @return returns TaskService
     */
    @WebEndpoint(name = "TaskServiceSoap11")
    public TaskService getTaskServiceSoap11(WebServiceFeature... features) {
        return super.getPort(new QName("http://enum.element.webservice.remote.oryx.com", "TaskServiceSoap11"), TaskService.class, features);
    }

}
