package com.oryx.remote.webservice.element._enum;

import javax.xml.namespace.QName;
import javax.xml.ws.*;
import java.net.MalformedURLException;
import java.net.URL;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.2.10
 * Generated source version: 2.2
 */
@WebServiceClient(name = "ThirdPartyServices", targetNamespace = "http://enum.element.webservice.remote.oryx.com", wsdlLocation = "http://localhost:8680/oryx-server/ThirdPartyService.wsdl")
public class ThirdPartyServices
        extends Service {

    private final static URL THIRDPARTYSERVICES_WSDL_LOCATION;
    private final static WebServiceException THIRDPARTYSERVICES_EXCEPTION;
    private final static QName THIRDPARTYSERVICES_QNAME = new QName("http://enum.element.webservice.remote.oryx.com", "ThirdPartyServices");

    static {
        URL url = null;
        WebServiceException e = null;
        try {
            url = new URL("http://localhost:8680/oryx-server/ThirdPartyService.wsdl");
        } catch (MalformedURLException ex) {
            e = new WebServiceException(ex);
        }
        THIRDPARTYSERVICES_WSDL_LOCATION = url;
        THIRDPARTYSERVICES_EXCEPTION = e;
    }

    public ThirdPartyServices() {
        super(__getWsdlLocation(), THIRDPARTYSERVICES_QNAME);
    }

    public ThirdPartyServices(WebServiceFeature... features) {
        super(__getWsdlLocation(), THIRDPARTYSERVICES_QNAME, features);
    }

    public ThirdPartyServices(URL wsdlLocation) {
        super(wsdlLocation, THIRDPARTYSERVICES_QNAME);
    }

    public ThirdPartyServices(URL wsdlLocation, WebServiceFeature... features) {
        super(wsdlLocation, THIRDPARTYSERVICES_QNAME, features);
    }

    public ThirdPartyServices(URL wsdlLocation, QName serviceName) {
        super(wsdlLocation, serviceName);
    }

    public ThirdPartyServices(URL wsdlLocation, QName serviceName, WebServiceFeature... features) {
        super(wsdlLocation, serviceName, features);
    }

    private static URL __getWsdlLocation() {
        if (THIRDPARTYSERVICES_EXCEPTION != null) {
            throw THIRDPARTYSERVICES_EXCEPTION;
        }
        return THIRDPARTYSERVICES_WSDL_LOCATION;
    }

    /**
     * @return returns ThirdPartyService
     */
    @WebEndpoint(name = "ThirdPartyServiceSoap11")
    public ThirdPartyService getThirdPartyServiceSoap11() {
        return super.getPort(new QName("http://enum.element.webservice.remote.oryx.com", "ThirdPartyServiceSoap11"), ThirdPartyService.class);
    }

    /**
     * @param features A list of {@link javax.xml.ws.WebServiceFeature} to configure on the proxy.  Supported features not in the <code>features</code> parameter will have their default values.
     * @return returns ThirdPartyService
     */
    @WebEndpoint(name = "ThirdPartyServiceSoap11")
    public ThirdPartyService getThirdPartyServiceSoap11(WebServiceFeature... features) {
        return super.getPort(new QName("http://enum.element.webservice.remote.oryx.com", "ThirdPartyServiceSoap11"), ThirdPartyService.class, features);
    }

}
