package com.oryx.remote.webservice.element._enum;

import javax.xml.namespace.QName;
import javax.xml.ws.*;
import java.net.MalformedURLException;
import java.net.URL;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.2.10
 * Generated source version: 2.2
 */
@WebServiceClient(name = "UidServices", targetNamespace = "http://enum.element.webservice.remote.oryx.com", wsdlLocation = "http://localhost:8680/oryx-server/UidService.wsdl")
public class UidServices
        extends Service {

    private final static URL UIDSERVICES_WSDL_LOCATION;
    private final static WebServiceException UIDSERVICES_EXCEPTION;
    private final static QName UIDSERVICES_QNAME = new QName("http://enum.element.webservice.remote.oryx.com", "UidServices");

    static {
        URL url = null;
        WebServiceException e = null;
        try {
            url = new URL("http://localhost:8680/oryx-server/UidService.wsdl");
        } catch (MalformedURLException ex) {
            e = new WebServiceException(ex);
        }
        UIDSERVICES_WSDL_LOCATION = url;
        UIDSERVICES_EXCEPTION = e;
    }

    public UidServices() {
        super(__getWsdlLocation(), UIDSERVICES_QNAME);
    }

    public UidServices(WebServiceFeature... features) {
        super(__getWsdlLocation(), UIDSERVICES_QNAME, features);
    }

    public UidServices(URL wsdlLocation) {
        super(wsdlLocation, UIDSERVICES_QNAME);
    }

    public UidServices(URL wsdlLocation, WebServiceFeature... features) {
        super(wsdlLocation, UIDSERVICES_QNAME, features);
    }

    public UidServices(URL wsdlLocation, QName serviceName) {
        super(wsdlLocation, serviceName);
    }

    public UidServices(URL wsdlLocation, QName serviceName, WebServiceFeature... features) {
        super(wsdlLocation, serviceName, features);
    }

    private static URL __getWsdlLocation() {
        if (UIDSERVICES_EXCEPTION != null) {
            throw UIDSERVICES_EXCEPTION;
        }
        return UIDSERVICES_WSDL_LOCATION;
    }

    /**
     * @return returns UidService
     */
    @WebEndpoint(name = "UidServiceSoap11")
    public UidService getUidServiceSoap11() {
        return super.getPort(new QName("http://enum.element.webservice.remote.oryx.com", "UidServiceSoap11"), UidService.class);
    }

    /**
     * @param features A list of {@link javax.xml.ws.WebServiceFeature} to configure on the proxy.  Supported features not in the <code>features</code> parameter will have their default values.
     * @return returns UidService
     */
    @WebEndpoint(name = "UidServiceSoap11")
    public UidService getUidServiceSoap11(WebServiceFeature... features) {
        return super.getPort(new QName("http://enum.element.webservice.remote.oryx.com", "UidServiceSoap11"), UidService.class, features);
    }

}
