package com.oryx.remote.webservice.element._enum;

import javax.xml.namespace.QName;
import javax.xml.ws.*;
import java.net.MalformedURLException;
import java.net.URL;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.2.10
 * Generated source version: 2.2
 */
@WebServiceClient(name = "UpgradesServices", targetNamespace = "http://enum.element.webservice.remote.oryx.com", wsdlLocation = "http://localhost:8680/oryx-server/UpgradesService.wsdl")
public class UpgradesServices
        extends Service {

    private final static URL UPGRADESSERVICES_WSDL_LOCATION;
    private final static WebServiceException UPGRADESSERVICES_EXCEPTION;
    private final static QName UPGRADESSERVICES_QNAME = new QName("http://enum.element.webservice.remote.oryx.com", "UpgradesServices");

    static {
        URL url = null;
        WebServiceException e = null;
        try {
            url = new URL("http://localhost:8680/oryx-server/UpgradesService.wsdl");
        } catch (MalformedURLException ex) {
            e = new WebServiceException(ex);
        }
        UPGRADESSERVICES_WSDL_LOCATION = url;
        UPGRADESSERVICES_EXCEPTION = e;
    }

    public UpgradesServices() {
        super(__getWsdlLocation(), UPGRADESSERVICES_QNAME);
    }

    public UpgradesServices(WebServiceFeature... features) {
        super(__getWsdlLocation(), UPGRADESSERVICES_QNAME, features);
    }

    public UpgradesServices(URL wsdlLocation) {
        super(wsdlLocation, UPGRADESSERVICES_QNAME);
    }

    public UpgradesServices(URL wsdlLocation, WebServiceFeature... features) {
        super(wsdlLocation, UPGRADESSERVICES_QNAME, features);
    }

    public UpgradesServices(URL wsdlLocation, QName serviceName) {
        super(wsdlLocation, serviceName);
    }

    public UpgradesServices(URL wsdlLocation, QName serviceName, WebServiceFeature... features) {
        super(wsdlLocation, serviceName, features);
    }

    private static URL __getWsdlLocation() {
        if (UPGRADESSERVICES_EXCEPTION != null) {
            throw UPGRADESSERVICES_EXCEPTION;
        }
        return UPGRADESSERVICES_WSDL_LOCATION;
    }

    /**
     * @return returns UpgradesService
     */
    @WebEndpoint(name = "UpgradesServiceSoap11")
    public UpgradesService getUpgradesServiceSoap11() {
        return super.getPort(new QName("http://enum.element.webservice.remote.oryx.com", "UpgradesServiceSoap11"), UpgradesService.class);
    }

    /**
     * @param features A list of {@link javax.xml.ws.WebServiceFeature} to configure on the proxy.  Supported features not in the <code>features</code> parameter will have their default values.
     * @return returns UpgradesService
     */
    @WebEndpoint(name = "UpgradesServiceSoap11")
    public UpgradesService getUpgradesServiceSoap11(WebServiceFeature... features) {
        return super.getPort(new QName("http://enum.element.webservice.remote.oryx.com", "UpgradesServiceSoap11"), UpgradesService.class, features);
    }

}
