LOCK TABLES T_USER WRITE;
INSERT INTO T_USER (ID,VERSION,DOMAIN_CODE,CREATED_BY,CREATE_DATE,UPDATE_DATE,UPDATED_BY,CANCEL_DATE,CANCELED_BY,CHECK_CANCEL,CODE,EMAIL,LAST_CONNECTION,LOGIN,PASSWORD,USER_ROLE,STATUS,PERSON_ID)
    VALUES (unhex(replace(uuid(),'-','')),null,null,null,{ts '2017-08-14 13:06:52'},{ts '2017-08-14 13:06:52'},null,null,null,false,'8SQUZ2DF0W','sami.mbarki@gmail.com',null,'sami','sami241180','ROLE_ADMIN','ACTIVE',null);
UNLOCK TABLES;