package com.oryx.remote.webservice.element._enum;

import javax.xml.namespace.QName;
import javax.xml.ws.*;
import java.net.MalformedURLException;
import java.net.URL;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.2.10
 * Generated source version: 2.2
 */
@WebServiceClient(name = "AdressServices", targetNamespace = "http://enum.element.webservice.remote.oryx.com", wsdlLocation = "http://localhost:8680/oryx-server/AdressService.wsdl")
public class AdressServices
        extends Service {

    private final static URL ADRESSSERVICES_WSDL_LOCATION;
    private final static WebServiceException ADRESSSERVICES_EXCEPTION;
    private final static QName ADRESSSERVICES_QNAME = new QName("http://enum.element.webservice.remote.oryx.com", "AdressServices");

    static {
        URL url = null;
        WebServiceException e = null;
        try {
            url = new URL("http://localhost:8680/oryx-server/AdressService.wsdl");
        } catch (MalformedURLException ex) {
            e = new WebServiceException(ex);
        }
        ADRESSSERVICES_WSDL_LOCATION = url;
        ADRESSSERVICES_EXCEPTION = e;
    }

    public AdressServices() {
        super(__getWsdlLocation(), ADRESSSERVICES_QNAME);
    }

    public AdressServices(WebServiceFeature... features) {
        super(__getWsdlLocation(), ADRESSSERVICES_QNAME, features);
    }

    public AdressServices(URL wsdlLocation) {
        super(wsdlLocation, ADRESSSERVICES_QNAME);
    }

    public AdressServices(URL wsdlLocation, WebServiceFeature... features) {
        super(wsdlLocation, ADRESSSERVICES_QNAME, features);
    }

    public AdressServices(URL wsdlLocation, QName serviceName) {
        super(wsdlLocation, serviceName);
    }

    public AdressServices(URL wsdlLocation, QName serviceName, WebServiceFeature... features) {
        super(wsdlLocation, serviceName, features);
    }

    private static URL __getWsdlLocation() {
        if (ADRESSSERVICES_EXCEPTION != null) {
            throw ADRESSSERVICES_EXCEPTION;
        }
        return ADRESSSERVICES_WSDL_LOCATION;
    }

    /**
     * @return returns AdressService
     */
    @WebEndpoint(name = "AdressServiceSoap11")
    public AdressService getAdressServiceSoap11() {
        return super.getPort(new QName("http://enum.element.webservice.remote.oryx.com", "AdressServiceSoap11"), AdressService.class);
    }

    /**
     * @param features A list of {@link javax.xml.ws.WebServiceFeature} to configure on the proxy.  Supported features not in the <code>features</code> parameter will have their default values.
     * @return returns AdressService
     */
    @WebEndpoint(name = "AdressServiceSoap11")
    public AdressService getAdressServiceSoap11(WebServiceFeature... features) {
        return super.getPort(new QName("http://enum.element.webservice.remote.oryx.com", "AdressServiceSoap11"), AdressService.class, features);
    }

}
