package com.oryx.remote.webservice.element._enum;

import javax.xml.namespace.QName;
import javax.xml.ws.*;
import java.net.MalformedURLException;
import java.net.URL;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.2.10
 * Generated source version: 2.2
 */
@WebServiceClient(name = "AnnexServices", targetNamespace = "http://enum.element.webservice.remote.oryx.com", wsdlLocation = "http://localhost:8680/oryx-server/AnnexService.wsdl")
public class AnnexServices
        extends Service {

    private final static URL ANNEXSERVICES_WSDL_LOCATION;
    private final static WebServiceException ANNEXSERVICES_EXCEPTION;
    private final static QName ANNEXSERVICES_QNAME = new QName("http://enum.element.webservice.remote.oryx.com", "AnnexServices");

    static {
        URL url = null;
        WebServiceException e = null;
        try {
            url = new URL("http://localhost:8680/oryx-server/AnnexService.wsdl");
        } catch (MalformedURLException ex) {
            e = new WebServiceException(ex);
        }
        ANNEXSERVICES_WSDL_LOCATION = url;
        ANNEXSERVICES_EXCEPTION = e;
    }

    public AnnexServices() {
        super(__getWsdlLocation(), ANNEXSERVICES_QNAME);
    }

    public AnnexServices(WebServiceFeature... features) {
        super(__getWsdlLocation(), ANNEXSERVICES_QNAME, features);
    }

    public AnnexServices(URL wsdlLocation) {
        super(wsdlLocation, ANNEXSERVICES_QNAME);
    }

    public AnnexServices(URL wsdlLocation, WebServiceFeature... features) {
        super(wsdlLocation, ANNEXSERVICES_QNAME, features);
    }

    public AnnexServices(URL wsdlLocation, QName serviceName) {
        super(wsdlLocation, serviceName);
    }

    public AnnexServices(URL wsdlLocation, QName serviceName, WebServiceFeature... features) {
        super(wsdlLocation, serviceName, features);
    }

    private static URL __getWsdlLocation() {
        if (ANNEXSERVICES_EXCEPTION != null) {
            throw ANNEXSERVICES_EXCEPTION;
        }
        return ANNEXSERVICES_WSDL_LOCATION;
    }

    /**
     * @return returns AnnexService
     */
    @WebEndpoint(name = "AnnexServiceSoap11")
    public AnnexService getAnnexServiceSoap11() {
        return super.getPort(new QName("http://enum.element.webservice.remote.oryx.com", "AnnexServiceSoap11"), AnnexService.class);
    }

    /**
     * @param features A list of {@link javax.xml.ws.WebServiceFeature} to configure on the proxy.  Supported features not in the <code>features</code> parameter will have their default values.
     * @return returns AnnexService
     */
    @WebEndpoint(name = "AnnexServiceSoap11")
    public AnnexService getAnnexServiceSoap11(WebServiceFeature... features) {
        return super.getPort(new QName("http://enum.element.webservice.remote.oryx.com", "AnnexServiceSoap11"), AnnexService.class, features);
    }

}
