package com.oryx.remote.webservice.element._enum;

import javax.xml.namespace.QName;
import javax.xml.ws.*;
import java.net.MalformedURLException;
import java.net.URL;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.2.10
 * Generated source version: 2.2
 */
@WebServiceClient(name = "HealthCheckServices", targetNamespace = "http://enum.element.webservice.remote.oryx.com", wsdlLocation = "http://localhost:8680/oryx-server/HealthCheckService.wsdl")
public class HealthCheckServices
        extends Service {

    private final static URL HEALTHCHECKSERVICES_WSDL_LOCATION;
    private final static WebServiceException HEALTHCHECKSERVICES_EXCEPTION;
    private final static QName HEALTHCHECKSERVICES_QNAME = new QName("http://enum.element.webservice.remote.oryx.com", "HealthCheckServices");

    static {
        URL url = null;
        WebServiceException e = null;
        try {
            url = new URL("http://localhost:8680/oryx-server/HealthCheckService.wsdl");
        } catch (MalformedURLException ex) {
            e = new WebServiceException(ex);
        }
        HEALTHCHECKSERVICES_WSDL_LOCATION = url;
        HEALTHCHECKSERVICES_EXCEPTION = e;
    }

    public HealthCheckServices() {
        super(__getWsdlLocation(), HEALTHCHECKSERVICES_QNAME);
    }

    public HealthCheckServices(WebServiceFeature... features) {
        super(__getWsdlLocation(), HEALTHCHECKSERVICES_QNAME, features);
    }

    public HealthCheckServices(URL wsdlLocation) {
        super(wsdlLocation, HEALTHCHECKSERVICES_QNAME);
    }

    public HealthCheckServices(URL wsdlLocation, WebServiceFeature... features) {
        super(wsdlLocation, HEALTHCHECKSERVICES_QNAME, features);
    }

    public HealthCheckServices(URL wsdlLocation, QName serviceName) {
        super(wsdlLocation, serviceName);
    }

    public HealthCheckServices(URL wsdlLocation, QName serviceName, WebServiceFeature... features) {
        super(wsdlLocation, serviceName, features);
    }

    private static URL __getWsdlLocation() {
        if (HEALTHCHECKSERVICES_EXCEPTION != null) {
            throw HEALTHCHECKSERVICES_EXCEPTION;
        }
        return HEALTHCHECKSERVICES_WSDL_LOCATION;
    }

    /**
     * @return returns HealthCheckService
     */
    @WebEndpoint(name = "HealthCheckServiceSoap11")
    public HealthCheckService getHealthCheckServiceSoap11() {
        return super.getPort(new QName("http://enum.element.webservice.remote.oryx.com", "HealthCheckServiceSoap11"), HealthCheckService.class);
    }

    /**
     * @param features A list of {@link javax.xml.ws.WebServiceFeature} to configure on the proxy.  Supported features not in the <code>features</code> parameter will have their default values.
     * @return returns HealthCheckService
     */
    @WebEndpoint(name = "HealthCheckServiceSoap11")
    public HealthCheckService getHealthCheckServiceSoap11(WebServiceFeature... features) {
        return super.getPort(new QName("http://enum.element.webservice.remote.oryx.com", "HealthCheckServiceSoap11"), HealthCheckService.class, features);
    }

}
