package com.oryx.remote.webservice.element._enum;

import javax.xml.namespace.QName;
import javax.xml.ws.*;
import java.net.MalformedURLException;
import java.net.URL;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.2.10
 * Generated source version: 2.2
 */
@WebServiceClient(name = "ProductCategoryServices", targetNamespace = "http://enum.element.webservice.remote.oryx.com", wsdlLocation = "http://localhost:8680/oryx-server/ProductCategoryService.wsdl")
public class ProductCategoryServices
        extends Service {

    private final static URL PRODUCTCATEGORYSERVICES_WSDL_LOCATION;
    private final static WebServiceException PRODUCTCATEGORYSERVICES_EXCEPTION;
    private final static QName PRODUCTCATEGORYSERVICES_QNAME = new QName("http://enum.element.webservice.remote.oryx.com", "ProductCategoryServices");

    static {
        URL url = null;
        WebServiceException e = null;
        try {
            url = new URL("http://localhost:8680/oryx-server/ProductCategoryService.wsdl");
        } catch (MalformedURLException ex) {
            e = new WebServiceException(ex);
        }
        PRODUCTCATEGORYSERVICES_WSDL_LOCATION = url;
        PRODUCTCATEGORYSERVICES_EXCEPTION = e;
    }

    public ProductCategoryServices() {
        super(__getWsdlLocation(), PRODUCTCATEGORYSERVICES_QNAME);
    }

    public ProductCategoryServices(WebServiceFeature... features) {
        super(__getWsdlLocation(), PRODUCTCATEGORYSERVICES_QNAME, features);
    }

    public ProductCategoryServices(URL wsdlLocation) {
        super(wsdlLocation, PRODUCTCATEGORYSERVICES_QNAME);
    }

    public ProductCategoryServices(URL wsdlLocation, WebServiceFeature... features) {
        super(wsdlLocation, PRODUCTCATEGORYSERVICES_QNAME, features);
    }

    public ProductCategoryServices(URL wsdlLocation, QName serviceName) {
        super(wsdlLocation, serviceName);
    }

    public ProductCategoryServices(URL wsdlLocation, QName serviceName, WebServiceFeature... features) {
        super(wsdlLocation, serviceName, features);
    }

    private static URL __getWsdlLocation() {
        if (PRODUCTCATEGORYSERVICES_EXCEPTION != null) {
            throw PRODUCTCATEGORYSERVICES_EXCEPTION;
        }
        return PRODUCTCATEGORYSERVICES_WSDL_LOCATION;
    }

    /**
     * @return returns ProductCategoryService
     */
    @WebEndpoint(name = "ProductCategoryServiceSoap11")
    public ProductCategoryService getProductCategoryServiceSoap11() {
        return super.getPort(new QName("http://enum.element.webservice.remote.oryx.com", "ProductCategoryServiceSoap11"), ProductCategoryService.class);
    }

    /**
     * @param features A list of {@link javax.xml.ws.WebServiceFeature} to configure on the proxy.  Supported features not in the <code>features</code> parameter will have their default values.
     * @return returns ProductCategoryService
     */
    @WebEndpoint(name = "ProductCategoryServiceSoap11")
    public ProductCategoryService getProductCategoryServiceSoap11(WebServiceFeature... features) {
        return super.getPort(new QName("http://enum.element.webservice.remote.oryx.com", "ProductCategoryServiceSoap11"), ProductCategoryService.class, features);
    }

}
