package com.oryx.remote.webservice.element._enum;

import javax.xml.namespace.QName;
import javax.xml.ws.*;
import java.net.MalformedURLException;
import java.net.URL;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.2.10
 * Generated source version: 2.2
 */
@WebServiceClient(name = "ProductServices", targetNamespace = "http://enum.element.webservice.remote.oryx.com", wsdlLocation = "http://localhost:8680/oryx-server/ProductService.wsdl")
public class ProductServices
        extends Service {

    private final static URL PRODUCTSERVICES_WSDL_LOCATION;
    private final static WebServiceException PRODUCTSERVICES_EXCEPTION;
    private final static QName PRODUCTSERVICES_QNAME = new QName("http://enum.element.webservice.remote.oryx.com", "ProductServices");

    static {
        URL url = null;
        WebServiceException e = null;
        try {
            url = new URL("http://localhost:8680/oryx-server/ProductService.wsdl");
        } catch (MalformedURLException ex) {
            e = new WebServiceException(ex);
        }
        PRODUCTSERVICES_WSDL_LOCATION = url;
        PRODUCTSERVICES_EXCEPTION = e;
    }

    public ProductServices() {
        super(__getWsdlLocation(), PRODUCTSERVICES_QNAME);
    }

    public ProductServices(WebServiceFeature... features) {
        super(__getWsdlLocation(), PRODUCTSERVICES_QNAME, features);
    }

    public ProductServices(URL wsdlLocation) {
        super(wsdlLocation, PRODUCTSERVICES_QNAME);
    }

    public ProductServices(URL wsdlLocation, WebServiceFeature... features) {
        super(wsdlLocation, PRODUCTSERVICES_QNAME, features);
    }

    public ProductServices(URL wsdlLocation, QName serviceName) {
        super(wsdlLocation, serviceName);
    }

    public ProductServices(URL wsdlLocation, QName serviceName, WebServiceFeature... features) {
        super(wsdlLocation, serviceName, features);
    }

    private static URL __getWsdlLocation() {
        if (PRODUCTSERVICES_EXCEPTION != null) {
            throw PRODUCTSERVICES_EXCEPTION;
        }
        return PRODUCTSERVICES_WSDL_LOCATION;
    }

    /**
     * @return returns ProductService
     */
    @WebEndpoint(name = "ProductServiceSoap11")
    public ProductService getProductServiceSoap11() {
        return super.getPort(new QName("http://enum.element.webservice.remote.oryx.com", "ProductServiceSoap11"), ProductService.class);
    }

    /**
     * @param features A list of {@link javax.xml.ws.WebServiceFeature} to configure on the proxy.  Supported features not in the <code>features</code> parameter will have their default values.
     * @return returns ProductService
     */
    @WebEndpoint(name = "ProductServiceSoap11")
    public ProductService getProductServiceSoap11(WebServiceFeature... features) {
        return super.getPort(new QName("http://enum.element.webservice.remote.oryx.com", "ProductServiceSoap11"), ProductService.class, features);
    }

}
