package com.oryx.remote.webservice.element._enum;

import com.oryx.remote.webservices.service.userviewservice.ViewRequest;
import com.oryx.remote.webservices.service.userviewservice.ViewResponse;

import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.jws.soap.SOAPBinding;
import javax.xml.bind.annotation.XmlSeeAlso;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.2.10
 * Generated source version: 2.2
 */
@WebService(name = "UserViewService", targetNamespace = "http://enum.element.webservice.remote.oryx.com")
@SOAPBinding(parameterStyle = SOAPBinding.ParameterStyle.BARE)
@XmlSeeAlso({
        com.oryx.remote.webservice.element.model.ObjectFactory.class,
        com.oryx.remote.webservice.element.model.system.ref.ObjectFactory.class,
        com.oryx.remote.webservice.element.operation.ObjectFactory.class,
        com.oryx.remote.webservice.element.view.system.ose.ObjectFactory.class,
        com.oryx.remote.webservices.service.userviewservice.ObjectFactory.class,
        com.oryx.remote.webservice.element._enum.ObjectFactory.class
})
public interface UserViewService {


    /**
     * @param viewRequest
     * @return returns com.oryx.remote.webservices.service.userviewservice.ViewResponse
     */
    @WebMethod
    @WebResult(name = "viewResponse", targetNamespace = "http://com/oryx/remote/webservices/service/userviewservice", partName = "viewResponse")
    public ViewResponse view(
            @WebParam(name = "viewRequest", targetNamespace = "http://com/oryx/remote/webservices/service/userviewservice", partName = "viewRequest")
                    ViewRequest viewRequest);

}
