package com.oryx.remote.webservice.element._enum;

import javax.xml.namespace.QName;
import javax.xml.ws.*;
import java.net.MalformedURLException;
import java.net.URL;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.2.10
 * Generated source version: 2.2
 */
@WebServiceClient(name = "UserServices", targetNamespace = "http://enum.element.webservice.remote.oryx.com", wsdlLocation = "http://localhost:8680/oryx-server/UserService.wsdl")
public class UserServices
        extends Service {

    private final static URL USERSERVICES_WSDL_LOCATION;
    private final static WebServiceException USERSERVICES_EXCEPTION;
    private final static QName USERSERVICES_QNAME = new QName("http://enum.element.webservice.remote.oryx.com", "UserServices");

    static {
        URL url = null;
        WebServiceException e = null;
        try {
            url = new URL("http://localhost:8680/oryx-server/UserService.wsdl");
        } catch (MalformedURLException ex) {
            e = new WebServiceException(ex);
        }
        USERSERVICES_WSDL_LOCATION = url;
        USERSERVICES_EXCEPTION = e;
    }

    public UserServices() {
        super(__getWsdlLocation(), USERSERVICES_QNAME);
    }

    public UserServices(WebServiceFeature... features) {
        super(__getWsdlLocation(), USERSERVICES_QNAME, features);
    }

    public UserServices(URL wsdlLocation) {
        super(wsdlLocation, USERSERVICES_QNAME);
    }

    public UserServices(URL wsdlLocation, WebServiceFeature... features) {
        super(wsdlLocation, USERSERVICES_QNAME, features);
    }

    public UserServices(URL wsdlLocation, QName serviceName) {
        super(wsdlLocation, serviceName);
    }

    public UserServices(URL wsdlLocation, QName serviceName, WebServiceFeature... features) {
        super(wsdlLocation, serviceName, features);
    }

    private static URL __getWsdlLocation() {
        if (USERSERVICES_EXCEPTION != null) {
            throw USERSERVICES_EXCEPTION;
        }
        return USERSERVICES_WSDL_LOCATION;
    }

    /**
     * @return returns UserService
     */
    @WebEndpoint(name = "UserServiceSoap11")
    public UserService getUserServiceSoap11() {
        return super.getPort(new QName("http://enum.element.webservice.remote.oryx.com", "UserServiceSoap11"), UserService.class);
    }

    /**
     * @param features A list of {@link javax.xml.ws.WebServiceFeature} to configure on the proxy.  Supported features not in the <code>features</code> parameter will have their default values.
     * @return returns UserService
     */
    @WebEndpoint(name = "UserServiceSoap11")
    public UserService getUserServiceSoap11(WebServiceFeature... features) {
        return super.getPort(new QName("http://enum.element.webservice.remote.oryx.com", "UserServiceSoap11"), UserService.class, features);
    }

}
