package com.oryx.remote.webservice.element._enum;

import javax.xml.namespace.QName;
import javax.xml.ws.*;
import java.net.MalformedURLException;
import java.net.URL;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.2.10
 * Generated source version: 2.2
 */
@WebServiceClient(name = "UserViewServices", targetNamespace = "http://enum.element.webservice.remote.oryx.com", wsdlLocation = "http://localhost:8680/oryx-server/UserViewService.wsdl")
public class UserViewServices
        extends Service {

    private final static URL USERVIEWSERVICES_WSDL_LOCATION;
    private final static WebServiceException USERVIEWSERVICES_EXCEPTION;
    private final static QName USERVIEWSERVICES_QNAME = new QName("http://enum.element.webservice.remote.oryx.com", "UserViewServices");

    static {
        URL url = null;
        WebServiceException e = null;
        try {
            url = new URL("http://localhost:8680/oryx-server/UserViewService.wsdl");
        } catch (MalformedURLException ex) {
            e = new WebServiceException(ex);
        }
        USERVIEWSERVICES_WSDL_LOCATION = url;
        USERVIEWSERVICES_EXCEPTION = e;
    }

    public UserViewServices() {
        super(__getWsdlLocation(), USERVIEWSERVICES_QNAME);
    }

    public UserViewServices(WebServiceFeature... features) {
        super(__getWsdlLocation(), USERVIEWSERVICES_QNAME, features);
    }

    public UserViewServices(URL wsdlLocation) {
        super(wsdlLocation, USERVIEWSERVICES_QNAME);
    }

    public UserViewServices(URL wsdlLocation, WebServiceFeature... features) {
        super(wsdlLocation, USERVIEWSERVICES_QNAME, features);
    }

    public UserViewServices(URL wsdlLocation, QName serviceName) {
        super(wsdlLocation, serviceName);
    }

    public UserViewServices(URL wsdlLocation, QName serviceName, WebServiceFeature... features) {
        super(wsdlLocation, serviceName, features);
    }

    private static URL __getWsdlLocation() {
        if (USERVIEWSERVICES_EXCEPTION != null) {
            throw USERVIEWSERVICES_EXCEPTION;
        }
        return USERVIEWSERVICES_WSDL_LOCATION;
    }

    /**
     * @return returns UserViewService
     */
    @WebEndpoint(name = "UserViewServiceSoap11")
    public UserViewService getUserViewServiceSoap11() {
        return super.getPort(new QName("http://enum.element.webservice.remote.oryx.com", "UserViewServiceSoap11"), UserViewService.class);
    }

    /**
     * @param features A list of {@link javax.xml.ws.WebServiceFeature} to configure on the proxy.  Supported features not in the <code>features</code> parameter will have their default values.
     * @return returns UserViewService
     */
    @WebEndpoint(name = "UserViewServiceSoap11")
    public UserViewService getUserViewServiceSoap11(WebServiceFeature... features) {
        return super.getPort(new QName("http://enum.element.webservice.remote.oryx.com", "UserViewServiceSoap11"), UserViewService.class, features);
    }

}
